#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "src/std/jiang/text/generated/xid.jiang");
const MAX_SCALAR = 0x10ffff;
const CHUNK_SCALARS = 512;
const CHUNK_BYTES = CHUNK_SCALARS / 8;

function scalarText(value) {
  return String.fromCodePoint(value);
}

function buildSet(property) {
  const re = new RegExp(`^\\p{${property}}$`, "u");
  const values = new Set();

  for (let scalar = 0; scalar <= MAX_SCALAR; scalar += 1) {
    if (scalar >= 0xd800 && scalar <= 0xdfff) {
      continue;
    }
    if (re.test(scalarText(scalar))) {
      values.add(scalar);
    }
  }
  return values;
}

function buildChunk(set, chunkId) {
  const bytes = new Array(CHUNK_BYTES).fill(0);
  const start = chunkId * CHUNK_SCALARS;
  for (let offset = 0; offset < CHUNK_SCALARS; offset += 1) {
    const scalar = start + offset;
    if (scalar > MAX_SCALAR) {
      break;
    }
    if (set.has(scalar)) {
      bytes[Math.floor(offset / 8)] |= 1 << (offset % 8);
    }
  }
  return bytes;
}

function buildTrie(startSet, continueSet) {
  const chunkCount = Math.ceil((MAX_SCALAR + 1) / CHUNK_SCALARS);
  const leafKeys = new Map();
  const leafChunks = [];
  const startTrie = [];
  const continueTrie = [];

  function internChunk(bytes) {
    const key = bytes.join(",");
    const existing = leafKeys.get(key);
    if (existing !== undefined) {
      return existing;
    }
    const index = leafChunks.length;
    leafKeys.set(key, index);
    leafChunks.push(bytes);
    return index;
  }

  for (let chunkId = 0; chunkId < chunkCount; chunkId += 1) {
    startTrie.push(internChunk(buildChunk(startSet, chunkId)));
    continueTrie.push(internChunk(buildChunk(continueSet, chunkId)));
  }

  return {
    chunkCount,
    startTrie,
    continueTrie,
    leaf: leafChunks.flat(),
    leafCount: leafChunks.length,
  };
}

function wrapValues(values, indent, perLine) {
  const lines = [];
  for (let index = 0; index < values.length; index += perLine) {
    const chunk = values.slice(index, index + perLine);
    const suffix = index + perLine < values.length ? "," : "";
    lines.push(`${indent}${chunk.join(", ")}${suffix}`);
  }
  return lines;
}

function emitArray(type, name, values, perLine) {
  return [
    `${type}[${values.length}] ${name} = [`,
    ...wrapValues(values, "    ", perLine),
    "];",
  ].join("\n");
}

const startSet = buildSet("XID_Start");
const continueSet = buildSet("XID_Continue");
const trie = buildTrie(startSet, continueSet);

const output = [
  "// Generated by script/gen_unicode_xid.js.",
  `// Unicode version: ${process.versions.unicode}.`,
  "// Do not edit by hand.",
  "",
  `const Int MAX_SCALAR = ${MAX_SCALAR};`,
  `const Int CHUNK_SCALARS = ${CHUNK_SCALARS};`,
  `const Int CHUNK_BYTES = ${CHUNK_BYTES};`,
  "",
  emitArray("UInt16", "TRIE_START", trie.startTrie, 16),
  "",
  emitArray("UInt16", "TRIE_CONTINUE", trie.continueTrie, 16),
  "",
  emitArray("UInt8", "LEAF", trie.leaf, 16),
  "",
  "public Bool is_xid_start(Int scalar) {",
  "    return contains_start(scalar);",
  "}",
  "",
  "public Bool is_xid_continue(Int scalar) {",
  "    return contains_continue(scalar);",
  "}",
  "",
  "Bool contains_start(Int scalar) {",
  "    if (scalar < 0 || scalar > MAX_SCALAR) { return false; }",
  "    return contains_leaf(Int(TRIE_START[scalar / CHUNK_SCALARS]), scalar % CHUNK_SCALARS);",
  "}",
  "",
  "Bool contains_continue(Int scalar) {",
  "    if (scalar < 0 || scalar > MAX_SCALAR) { return false; }",
  "    return contains_leaf(Int(TRIE_CONTINUE[scalar / CHUNK_SCALARS]), scalar % CHUNK_SCALARS);",
  "}",
  "",
  "Bool contains_leaf(Int leaf_index, Int bit_id) {",
  "    Int byte_index = bit_id / 8;",
  "    Int bit = bit_id % 8;",
  "    Int offset = leaf_index * CHUNK_BYTES + byte_index;",
  "    Int byte = Int(LEAF[offset]);",
  "    return ((byte >> bit) & 1) != 0;",
  "}",
  "",
].join("\n");

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, output);
console.log(`wrote ${path.relative(ROOT, OUT)}`);
console.log(`XID_Start scalars: ${startSet.size}`);
console.log(`XID_Continue scalars: ${continueSet.size}`);
console.log(`chunks: ${trie.chunkCount}`);
console.log(`unique leaf chunks: ${trie.leafCount}`);
console.log(`leaf bytes: ${trie.leaf.length}`);
