#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build"
OUT_C="$BUILD_DIR/stage2_minimal.c"
OUT_O="$BUILD_DIR/stage2_minimal.o"
LARGE_C="$BUILD_DIR/stage2_large_minimal.c"
LARGE_O="$BUILD_DIR/stage2_large_minimal.o"
BOOL_C="$BUILD_DIR/stage2_bool_minimal.c"
BOOL_O="$BUILD_DIR/stage2_bool_minimal.o"
VOID_C="$BUILD_DIR/stage2_void_minimal.c"
VOID_O="$BUILD_DIR/stage2_void_minimal.o"
IF_C="$BUILD_DIR/stage2_if_minimal.c"
IF_O="$BUILD_DIR/stage2_if_minimal.o"
WHILE_C="$BUILD_DIR/stage2_while_minimal.c"
WHILE_O="$BUILD_DIR/stage2_while_minimal.o"
BINARY_C="$BUILD_DIR/stage2_binary_ops_minimal.c"
BINARY_O="$BUILD_DIR/stage2_binary_ops_minimal.o"
LOCALS_C="$BUILD_DIR/stage2_locals_minimal.c"
LOCALS_O="$BUILD_DIR/stage2_locals_minimal.o"
ASSIGN_C="$BUILD_DIR/stage2_assign_minimal.c"
ASSIGN_O="$BUILD_DIR/stage2_assign_minimal.o"
MULTI_C="$BUILD_DIR/stage2_multi_file_minimal.c"
MULTI_O="$BUILD_DIR/stage2_multi_file_minimal.o"
MULTI_ENUM_C="$BUILD_DIR/stage2_multi_file_enum_minimal.c"
MULTI_ENUM_O="$BUILD_DIR/stage2_multi_file_enum_minimal.o"
MULTI_STRUCT_C="$BUILD_DIR/stage2_multi_file_struct_minimal.c"
MULTI_STRUCT_O="$BUILD_DIR/stage2_multi_file_struct_minimal.o"
STRUCT_C="$BUILD_DIR/stage2_struct_minimal.c"
STRUCT_O="$BUILD_DIR/stage2_struct_minimal.o"
ENUM_C="$BUILD_DIR/stage2_enum_minimal.c"
ENUM_O="$BUILD_DIR/stage2_enum_minimal.o"
FIELDS_C="$BUILD_DIR/stage2_fields_minimal.c"
FIELDS_O="$BUILD_DIR/stage2_fields_minimal.o"

bash "$PROJECT_ROOT/script/build_stage2.sh"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/minimal.jiang" > "$OUT_C"

rg -q '^#include <stdint.h>$' "$OUT_C"
rg -q 'long long add\(long long a, long long b\);' "$OUT_C"
rg -q 'int main\(void\);' "$OUT_C"
rg -q 'return \(a \+ b\);' "$OUT_C"
rg -q 'return add\(40, 2\);' "$OUT_C"

cc -x c -std=c99 -Wall -Wextra -Werror -c "$OUT_C" -o "$OUT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/large_minimal.jiang" > "$LARGE_C"
rg -q 'long long add15\(long long x\);' "$LARGE_C"
rg -q 'return add15' "$LARGE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$LARGE_C" -o "$LARGE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/bool_minimal.jiang" > "$BOOL_C"
rg -q '^int flag\(long long x\);$' "$BOOL_C"
rg -q '^    if \(flag\(1\)\) \{$' "$BOOL_C"
rg -q '^    return 1;$' "$BOOL_C"
rg -q '^    return 0;$' "$BOOL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$BOOL_C" -o "$BOOL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/void_minimal.jiang" > "$VOID_C"
rg -q '^void noop\(void\);$' "$VOID_C"
rg -q '^    return;$' "$VOID_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$VOID_C" -o "$VOID_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/if_minimal.jiang" > "$IF_C"
rg -q '^long long choose\(int flag\);$' "$IF_C"
rg -q '^    if \(flag\) \{$' "$IF_C"
rg -q '^    \} else \{$' "$IF_C"
rg -q '^    return 1;$' "$IF_C"
rg -q '^    return 2;$' "$IF_C"
rg -q 'return choose\(0\);' "$IF_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$IF_C" -o "$IF_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/while_minimal.jiang" > "$WHILE_C"
rg -q '^long long loop_sum\(long long n\);$' "$WHILE_C"
rg -q '^    while \(i < n\) \{$' "$WHILE_C"
rg -q '\(sum = \(sum \+ i\)\);' "$WHILE_C"
rg -q '\(i = \(i \+ 1\)\);' "$WHILE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$WHILE_C" -o "$WHILE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/binary_ops_minimal.jiang" > "$BINARY_C"
rg -q 'return \(\(a \* b\) - \(a / b\)\);' "$BINARY_C"
rg -q 'if \(a == b\) \{' "$BINARY_C"
rg -q 'if \(a != b\) \{' "$BINARY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$BINARY_C" -o "$BINARY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/locals_minimal.jiang" > "$LOCALS_C"
rg -q '^    long long next = \(value \+ value\);$' "$LOCALS_C"
rg -q '^    long long result = twice\(21\);$' "$LOCALS_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$LOCALS_C" -o "$LOCALS_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/assign_minimal.jiang" > "$ASSIGN_C"
rg -q '^    long long value = 1;$' "$ASSIGN_C"
rg -q '^    \(value = \(value \+ x\)\);$' "$ASSIGN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ASSIGN_C" -o "$ASSIGN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_minimal.jiang" > "$MULTI_C"
rg -q '^long long helper_add\(long long a, long long b\);$' "$MULTI_C"
rg -q 'return helper_add\(20, 22\);' "$MULTI_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_C" -o "$MULTI_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_enum_minimal.jiang" > "$MULTI_ENUM_C"
rg -q '^typedef enum Mode \{$' "$MULTI_ENUM_C"
rg -q '^    Mode_read,$' "$MULTI_ENUM_C"
rg -q '^    Mode_write$' "$MULTI_ENUM_C"
rg -q 'return Mode_read;' "$MULTI_ENUM_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_ENUM_C" -o "$MULTI_ENUM_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_struct_minimal.jiang" > "$MULTI_STRUCT_C"
rg -q '^typedef struct Pair \{$' "$MULTI_STRUCT_C"
rg -q '^} Pair;$' "$MULTI_STRUCT_C"
rg -q 'Pair pair = \(Pair\)\{ \.left = 20, \.right = 22 \};' "$MULTI_STRUCT_C"
rg -q 'return \(pair.left \+ pair.right\);' "$MULTI_STRUCT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_STRUCT_C" -o "$MULTI_STRUCT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/struct_minimal.jiang" > "$STRUCT_C"
rg -q '^typedef struct Pair \{$' "$STRUCT_C"
rg -q '^} Pair;$' "$STRUCT_C"
rg -q '^long long sum_pair\(Pair pair\);$' "$STRUCT_C"
rg -q 'return \(pair.left \+ pair.right\);' "$STRUCT_C"
rg -q 'Pair pair = \(Pair\)\{ \.left = 20, \.right = 22 \};' "$STRUCT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$STRUCT_C" -o "$STRUCT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/enum_minimal.jiang" > "$ENUM_C"
rg -q '^typedef enum Mode \{$' "$ENUM_C"
rg -q '^    Mode_read,$' "$ENUM_C"
rg -q '^    Mode_write$' "$ENUM_C"
rg -q '^} Mode;$' "$ENUM_C"
rg -q 'if \(mode == Mode_read\) \{' "$ENUM_C"
rg -q 'return code\(Mode_write\);' "$ENUM_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ENUM_C" -o "$ENUM_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/fields_minimal.jiang" > "$FIELDS_C"
rg -q 'Pair pair = \(Pair\)\{ \.left = 1, \.right = 2 \};' "$FIELDS_C"
rg -q '\(pair.left = \(pair.left \+ pair.right\)\);' "$FIELDS_C"
rg -q '^    return pair.left;$' "$FIELDS_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FIELDS_C" -o "$FIELDS_O"

echo "stage2 emit-c smoke passed"
