#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build"
OUT_C="$BUILD_DIR/stage2_minimal.c"
OUT_O="$BUILD_DIR/stage2_minimal.o"
LARGE_C="$BUILD_DIR/stage2_large_minimal.c"
LARGE_O="$BUILD_DIR/stage2_large_minimal.o"
BOOL_C="$BUILD_DIR/stage2_bool_minimal.c"
BOOL_O="$BUILD_DIR/stage2_bool_minimal.o"
UINT8_C="$BUILD_DIR/stage2_uint8_minimal.c"
UINT8_O="$BUILD_DIR/stage2_uint8_minimal.o"
UINT8_SLICE_C="$BUILD_DIR/stage2_uint8_slice_minimal.c"
UINT8_SLICE_O="$BUILD_DIR/stage2_uint8_slice_minimal.o"
VOID_C="$BUILD_DIR/stage2_void_minimal.c"
VOID_O="$BUILD_DIR/stage2_void_minimal.o"
IF_C="$BUILD_DIR/stage2_if_minimal.c"
IF_O="$BUILD_DIR/stage2_if_minimal.o"
WHILE_C="$BUILD_DIR/stage2_while_minimal.c"
WHILE_O="$BUILD_DIR/stage2_while_minimal.o"
BINARY_C="$BUILD_DIR/stage2_binary_ops_minimal.c"
BINARY_O="$BUILD_DIR/stage2_binary_ops_minimal.o"
LOCALS_C="$BUILD_DIR/stage2_locals_minimal.c"
LOCALS_O="$BUILD_DIR/stage2_locals_minimal.o"
ASSIGN_C="$BUILD_DIR/stage2_assign_minimal.c"
ASSIGN_O="$BUILD_DIR/stage2_assign_minimal.o"
MULTI_C="$BUILD_DIR/stage2_multi_file_minimal.c"
MULTI_O="$BUILD_DIR/stage2_multi_file_minimal.o"
MULTI_ENUM_C="$BUILD_DIR/stage2_multi_file_enum_minimal.c"
MULTI_ENUM_O="$BUILD_DIR/stage2_multi_file_enum_minimal.o"
MULTI_STRUCT_C="$BUILD_DIR/stage2_multi_file_struct_minimal.c"
MULTI_STRUCT_O="$BUILD_DIR/stage2_multi_file_struct_minimal.o"
STRUCT_C="$BUILD_DIR/stage2_struct_minimal.c"
STRUCT_O="$BUILD_DIR/stage2_struct_minimal.o"
ENUM_C="$BUILD_DIR/stage2_enum_minimal.c"
ENUM_O="$BUILD_DIR/stage2_enum_minimal.o"
FIELDS_C="$BUILD_DIR/stage2_fields_minimal.c"
FIELDS_O="$BUILD_DIR/stage2_fields_minimal.o"
NESTED_FIELDS_C="$BUILD_DIR/stage2_nested_fields_minimal.c"
NESTED_FIELDS_O="$BUILD_DIR/stage2_nested_fields_minimal.o"
CALL_RESULT_FIELD_C="$BUILD_DIR/stage2_call_result_field_minimal.c"
CALL_RESULT_FIELD_O="$BUILD_DIR/stage2_call_result_field_minimal.o"
PUBLIC_IMPORT_FUNCTION_C="$BUILD_DIR/stage2_public_import_function_minimal.c"
PUBLIC_IMPORT_FUNCTION_O="$BUILD_DIR/stage2_public_import_function_minimal.o"
PUBLIC_IMPORT_TYPE_C="$BUILD_DIR/stage2_public_import_type_minimal.c"
PUBLIC_IMPORT_TYPE_O="$BUILD_DIR/stage2_public_import_type_minimal.o"
NAMESPACED_IMPORT_C="$BUILD_DIR/stage2_namespaced_import_minimal.c"
NAMESPACED_IMPORT_O="$BUILD_DIR/stage2_namespaced_import_minimal.o"
NAMESPACED_STRUCT_IMPORT_C="$BUILD_DIR/stage2_namespaced_struct_import_minimal.c"
NAMESPACED_STRUCT_IMPORT_O="$BUILD_DIR/stage2_namespaced_struct_import_minimal.o"
NAMESPACED_ENUM_IMPORT_C="$BUILD_DIR/stage2_namespaced_enum_import_minimal.c"
NAMESPACED_ENUM_IMPORT_O="$BUILD_DIR/stage2_namespaced_enum_import_minimal.o"

bash "$PROJECT_ROOT/script/build_stage2.sh"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/minimal.jiang" > "$OUT_C"

rg -q '^#include <stdint.h>$' "$OUT_C"
rg -q 'long long add\(long long a, long long b\);' "$OUT_C"
rg -q 'int main\(void\);' "$OUT_C"
rg -q 'return \(a \+ b\);' "$OUT_C"
rg -q 'return add\(40, 2\);' "$OUT_C"

cc -x c -std=c99 -Wall -Wextra -Werror -c "$OUT_C" -o "$OUT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/large_minimal.jiang" > "$LARGE_C"
rg -q 'long long add15\(long long x\);' "$LARGE_C"
rg -q 'return add15' "$LARGE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$LARGE_C" -o "$LARGE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/bool_minimal.jiang" > "$BOOL_C"
rg -q '^int flag\(long long x\);$' "$BOOL_C"
rg -q '^    if \(flag\(1\)\) \{$' "$BOOL_C"
rg -q '^    return 1;$' "$BOOL_C"
rg -q '^    return 0;$' "$BOOL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$BOOL_C" -o "$BOOL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/uint8_minimal.jiang" > "$UINT8_C"
rg -q '^uint8_t id\(uint8_t value\);$' "$UINT8_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UINT8_C" -o "$UINT8_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/uint8_slice_minimal.jiang" > "$UINT8_SLICE_C"
rg -q '^typedef struct \{$' "$UINT8_SLICE_C"
rg -q '^} Slice_uint8_t;$' "$UINT8_SLICE_C"
rg -q '^Slice_uint8_t id\(Slice_uint8_t value\);$' "$UINT8_SLICE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UINT8_SLICE_C" -o "$UINT8_SLICE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/void_minimal.jiang" > "$VOID_C"
rg -q '^void noop\(void\);$' "$VOID_C"
rg -q '^    return;$' "$VOID_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$VOID_C" -o "$VOID_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/if_minimal.jiang" > "$IF_C"
rg -q '^long long choose\(int flag\);$' "$IF_C"
rg -q '^    if \(flag\) \{$' "$IF_C"
rg -q '^    \} else \{$' "$IF_C"
rg -q '^    return 1;$' "$IF_C"
rg -q '^    return 2;$' "$IF_C"
rg -q 'return choose\(0\);' "$IF_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$IF_C" -o "$IF_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/while_minimal.jiang" > "$WHILE_C"
rg -q '^long long loop_sum\(long long n\);$' "$WHILE_C"
rg -q '^    while \(i < n\) \{$' "$WHILE_C"
rg -q '\(sum = \(sum \+ i\)\);' "$WHILE_C"
rg -q '\(i = \(i \+ 1\)\);' "$WHILE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$WHILE_C" -o "$WHILE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/binary_ops_minimal.jiang" > "$BINARY_C"
rg -q 'return \(\(a \* b\) - \(a / b\)\);' "$BINARY_C"
rg -q 'if \(a == b\) \{' "$BINARY_C"
rg -q 'if \(a != b\) \{' "$BINARY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$BINARY_C" -o "$BINARY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/locals_minimal.jiang" > "$LOCALS_C"
rg -q '^    long long next = \(value \+ value\);$' "$LOCALS_C"
rg -q '^    long long result = twice\(21\);$' "$LOCALS_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$LOCALS_C" -o "$LOCALS_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/assign_minimal.jiang" > "$ASSIGN_C"
rg -q '^    long long value = 1;$' "$ASSIGN_C"
rg -q '^    \(value = \(value \+ x\)\);$' "$ASSIGN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ASSIGN_C" -o "$ASSIGN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_minimal.jiang" > "$MULTI_C"
rg -q '^long long helper_add\(long long a, long long b\);$' "$MULTI_C"
rg -q 'return helper_add\(20, 22\);' "$MULTI_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_C" -o "$MULTI_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_enum_minimal.jiang" > "$MULTI_ENUM_C"
rg -q '^typedef enum Mode \{$' "$MULTI_ENUM_C"
rg -q '^    Mode_read,$' "$MULTI_ENUM_C"
rg -q '^    Mode_write$' "$MULTI_ENUM_C"
rg -q '^    Mode mode = Mode_read;$' "$MULTI_ENUM_C"
rg -q '^    if \(mode == Mode_read\) \{$' "$MULTI_ENUM_C"
rg -q '^    return 1;$' "$MULTI_ENUM_C"
rg -q '^    return 0;$' "$MULTI_ENUM_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_ENUM_C" -o "$MULTI_ENUM_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_struct_minimal.jiang" > "$MULTI_STRUCT_C"
rg -q '^typedef struct Pair \{$' "$MULTI_STRUCT_C"
rg -q '^} Pair;$' "$MULTI_STRUCT_C"
rg -q 'Pair pair = \(Pair\)\{ \.left = 20, \.right = 22 \};' "$MULTI_STRUCT_C"
rg -q 'return \(pair.left \+ pair.right\);' "$MULTI_STRUCT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_STRUCT_C" -o "$MULTI_STRUCT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/struct_minimal.jiang" > "$STRUCT_C"
rg -q '^typedef struct Pair \{$' "$STRUCT_C"
rg -q '^} Pair;$' "$STRUCT_C"
rg -q '^long long sum_pair\(Pair pair\);$' "$STRUCT_C"
rg -q 'return \(pair.left \+ pair.right\);' "$STRUCT_C"
rg -q 'Pair pair = \(Pair\)\{ \.left = 20, \.right = 22 \};' "$STRUCT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$STRUCT_C" -o "$STRUCT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/enum_minimal.jiang" > "$ENUM_C"
rg -q '^typedef enum Mode \{$' "$ENUM_C"
rg -q '^    Mode_read,$' "$ENUM_C"
rg -q '^    Mode_write$' "$ENUM_C"
rg -q '^} Mode;$' "$ENUM_C"
rg -q 'if \(mode == Mode_read\) \{' "$ENUM_C"
rg -q 'return code\(Mode_write\);' "$ENUM_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ENUM_C" -o "$ENUM_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/fields_minimal.jiang" > "$FIELDS_C"
rg -q 'Pair pair = \(Pair\)\{ \.left = 1, \.right = 2 \};' "$FIELDS_C"
rg -q '\(pair.left = \(pair.left \+ pair.right\)\);' "$FIELDS_C"
rg -q '^    return pair.left;$' "$FIELDS_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FIELDS_C" -o "$FIELDS_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/nested_fields_minimal.jiang" > "$NESTED_FIELDS_C"
rg -q '^typedef struct Point \{$' "$NESTED_FIELDS_C"
rg -q '^typedef struct Box \{$' "$NESTED_FIELDS_C"
rg -q 'return box.point.x;' "$NESTED_FIELDS_C"
rg -q 'Box box = \(Box\)\{ \.point = \(Point\)\{ \.x = 42 \} \};' "$NESTED_FIELDS_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NESTED_FIELDS_C" -o "$NESTED_FIELDS_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/call_result_field_minimal.jiang" > "$CALL_RESULT_FIELD_C"
rg -q '^Box make_box\(void\);$' "$CALL_RESULT_FIELD_C"
rg -q 'return make_box\(\)\.point\.x;' "$CALL_RESULT_FIELD_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$CALL_RESULT_FIELD_C" -o "$CALL_RESULT_FIELD_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/public_import_function_minimal.jiang" > "$PUBLIC_IMPORT_FUNCTION_C"
rg -q '^long long public_add\(long long a, long long b\);$' "$PUBLIC_IMPORT_FUNCTION_C"
rg -q 'return public_add\(20, 22\);' "$PUBLIC_IMPORT_FUNCTION_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$PUBLIC_IMPORT_FUNCTION_C" -o "$PUBLIC_IMPORT_FUNCTION_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/public_import_type_minimal.jiang" > "$PUBLIC_IMPORT_TYPE_C"
rg -q '^typedef struct PublicPair \{$' "$PUBLIC_IMPORT_TYPE_C"
rg -q 'PublicPair pair = \(PublicPair\)\{ \.left = 20, \.right = 22 \};' "$PUBLIC_IMPORT_TYPE_C"
rg -q 'return \(pair.left \+ pair.right\);' "$PUBLIC_IMPORT_TYPE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$PUBLIC_IMPORT_TYPE_C" -o "$PUBLIC_IMPORT_TYPE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_import_minimal.jiang" > "$NAMESPACED_IMPORT_C"
rg -q '^long long helper_add\(long long a, long long b\);$' "$NAMESPACED_IMPORT_C"
rg -q 'return helper_add\(20, 22\);' "$NAMESPACED_IMPORT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_IMPORT_C" -o "$NAMESPACED_IMPORT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_struct_import_minimal.jiang" > "$NAMESPACED_STRUCT_IMPORT_C"
rg -q '^typedef struct Pair \{$' "$NAMESPACED_STRUCT_IMPORT_C"
rg -q 'Pair pair = \(Pair\)\{ \.left = 20, \.right = 22 \};' "$NAMESPACED_STRUCT_IMPORT_C"
rg -q 'return \(pair.left \+ pair.right\);' "$NAMESPACED_STRUCT_IMPORT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_STRUCT_IMPORT_C" -o "$NAMESPACED_STRUCT_IMPORT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_enum_import_minimal.jiang" > "$NAMESPACED_ENUM_IMPORT_C"
rg -q '^typedef enum Mode \{$' "$NAMESPACED_ENUM_IMPORT_C"
rg -q '^    Mode mode = Mode_read;$' "$NAMESPACED_ENUM_IMPORT_C"
rg -q '^    if \(mode == Mode_read\) \{$' "$NAMESPACED_ENUM_IMPORT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_ENUM_IMPORT_C" -o "$NAMESPACED_ENUM_IMPORT_O"

echo "stage2 emit-c smoke passed"
