#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build"

expect_fn_decl() {
    local ret="$1"
    local name="$2"
    local params="$3"
    local file="$4"
    rg -q "^${ret} .*${name}\\(${params}\\);$" "$file"
}

expect_type_start() {
    local kind="$1"
    local name="$2"
    local file="$3"
    rg -q "^typedef ${kind} .*${name} \\{$" "$file"
}

expect_type_end() {
    local name="$1"
    local file="$2"
    rg -q "^} .*${name};$" "$file"
}
OUT_C="$BUILD_DIR/stage2_minimal.c"
OUT_O="$BUILD_DIR/stage2_minimal.o"
LARGE_C="$BUILD_DIR/stage2_large_minimal.c"
LARGE_O="$BUILD_DIR/stage2_large_minimal.o"
BOOL_C="$BUILD_DIR/stage2_bool_minimal.c"
BOOL_O="$BUILD_DIR/stage2_bool_minimal.o"
UINT8_C="$BUILD_DIR/stage2_uint8_minimal.c"
UINT8_O="$BUILD_DIR/stage2_uint8_minimal.o"
UINT8_SLICE_C="$BUILD_DIR/stage2_uint8_slice_minimal.c"
UINT8_SLICE_O="$BUILD_DIR/stage2_uint8_slice_minimal.o"
SLICE_LENGTH_C="$BUILD_DIR/stage2_slice_length_minimal.c"
SLICE_LENGTH_O="$BUILD_DIR/stage2_slice_length_minimal.o"
SLICE_INDEX_C="$BUILD_DIR/stage2_slice_index_minimal.c"
SLICE_INDEX_O="$BUILD_DIR/stage2_slice_index_minimal.o"
SLICE_ASSIGN_C="$BUILD_DIR/stage2_slice_assign_minimal.c"
SLICE_ASSIGN_O="$BUILD_DIR/stage2_slice_assign_minimal.o"
SLICE_RETURN_LENGTH_C="$BUILD_DIR/stage2_slice_return_length_minimal.c"
SLICE_RETURN_LENGTH_O="$BUILD_DIR/stage2_slice_return_length_minimal.o"
ARRAY_C="$BUILD_DIR/stage2_array_minimal.c"
ARRAY_O="$BUILD_DIR/stage2_array_minimal.o"
INFER_ARRAY_LENGTH_C="$BUILD_DIR/stage2_infer_array_length_minimal.c"
INFER_ARRAY_LENGTH_O="$BUILD_DIR/stage2_infer_array_length_minimal.o"
TYPED_ARRAY_CONSTRUCTOR_C="$BUILD_DIR/stage2_typed_array_constructor_minimal.c"
TYPED_ARRAY_CONSTRUCTOR_O="$BUILD_DIR/stage2_typed_array_constructor_minimal.o"
TYPED_ARRAY_CONSTRUCTOR_INFER_C="$BUILD_DIR/stage2_typed_array_constructor_infer_minimal.c"
TYPED_ARRAY_CONSTRUCTOR_INFER_O="$BUILD_DIR/stage2_typed_array_constructor_infer_minimal.o"
ARRAY_ASSIGN_C="$BUILD_DIR/stage2_array_assign_minimal.c"
ARRAY_ASSIGN_O="$BUILD_DIR/stage2_array_assign_minimal.o"
UINT8_ARRAY_STRING_C="$BUILD_DIR/stage2_uint8_array_string_minimal.c"
UINT8_ARRAY_STRING_O="$BUILD_DIR/stage2_uint8_array_string_minimal.o"
INFER_UINT8_ARRAY_STRING_C="$BUILD_DIR/stage2_infer_uint8_array_string_minimal.c"
INFER_UINT8_ARRAY_STRING_O="$BUILD_DIR/stage2_infer_uint8_array_string_minimal.o"
NESTED_ARRAY_C="$BUILD_DIR/stage2_nested_array_minimal.c"
NESTED_ARRAY_O="$BUILD_DIR/stage2_nested_array_minimal.o"
STRUCT_ARRAY_FIELD_C="$BUILD_DIR/stage2_struct_array_field_minimal.c"
STRUCT_ARRAY_FIELD_O="$BUILD_DIR/stage2_struct_array_field_minimal.o"
EMPTY_TUPLE_RETURN_C="$BUILD_DIR/stage2_empty_tuple_return_minimal.c"
EMPTY_TUPLE_RETURN_O="$BUILD_DIR/stage2_empty_tuple_return_minimal.o"
EMPTY_TUPLE_BARE_RETURN_C="$BUILD_DIR/stage2_empty_tuple_bare_return_minimal.c"
EMPTY_TUPLE_BARE_RETURN_O="$BUILD_DIR/stage2_empty_tuple_bare_return_minimal.o"
IF_C="$BUILD_DIR/stage2_if_minimal.c"
IF_O="$BUILD_DIR/stage2_if_minimal.o"
WHILE_C="$BUILD_DIR/stage2_while_minimal.c"
WHILE_O="$BUILD_DIR/stage2_while_minimal.o"
BREAK_CONTINUE_C="$BUILD_DIR/stage2_break_continue_minimal.c"
BREAK_CONTINUE_O="$BUILD_DIR/stage2_break_continue_minimal.o"
FOR_RANGE_C="$BUILD_DIR/stage2_for_range_minimal.c"
FOR_RANGE_O="$BUILD_DIR/stage2_for_range_minimal.o"
FOR_INFER_RANGE_C="$BUILD_DIR/stage2_for_infer_range_minimal.c"
FOR_INFER_RANGE_O="$BUILD_DIR/stage2_for_infer_range_minimal.o"
FOR_ITEM_ARRAY_C="$BUILD_DIR/stage2_for_item_array_minimal.c"
FOR_ITEM_ARRAY_O="$BUILD_DIR/stage2_for_item_array_minimal.o"
FOR_INDEXED_C="$BUILD_DIR/stage2_for_indexed_minimal.c"
FOR_INDEXED_O="$BUILD_DIR/stage2_for_indexed_minimal.o"
FOR_INDEXED_TYPED_C="$BUILD_DIR/stage2_for_indexed_typed_minimal.c"
FOR_INDEXED_TYPED_O="$BUILD_DIR/stage2_for_indexed_typed_minimal.o"
FOR_INDEXED_TUPLE_BINDING_C="$BUILD_DIR/stage2_for_indexed_tuple_binding_minimal.c"
FOR_INDEXED_TUPLE_BINDING_O="$BUILD_DIR/stage2_for_indexed_tuple_binding_minimal.o"
FOR_MUTABLE_BINDING_C="$BUILD_DIR/stage2_for_mutable_binding_minimal.c"
FOR_MUTABLE_BINDING_O="$BUILD_DIR/stage2_for_mutable_binding_minimal.o"
FOR_INDEXED_MUTABLE_TUPLE_BINDING_C="$BUILD_DIR/stage2_for_indexed_mutable_tuple_binding_minimal.c"
FOR_INDEXED_MUTABLE_TUPLE_BINDING_O="$BUILD_DIR/stage2_for_indexed_mutable_tuple_binding_minimal.o"
FOR_TUPLE_BINDING_C="$BUILD_DIR/stage2_for_tuple_binding_minimal.c"
FOR_TUPLE_BINDING_O="$BUILD_DIR/stage2_for_tuple_binding_minimal.o"
FOR_TUPLE_BINDING_TYPED_C="$BUILD_DIR/stage2_for_tuple_binding_typed_minimal.c"
FOR_TUPLE_BINDING_TYPED_O="$BUILD_DIR/stage2_for_tuple_binding_typed_minimal.o"
SWITCH_ENUM_C="$BUILD_DIR/stage2_switch_enum_minimal.c"
SWITCH_ENUM_O="$BUILD_DIR/stage2_switch_enum_minimal.o"
ENUM_SWITCH_SHORTHAND_C="$BUILD_DIR/stage2_enum_switch_shorthand_minimal.c"
ENUM_SWITCH_SHORTHAND_O="$BUILD_DIR/stage2_enum_switch_shorthand_minimal.o"
STRUCT_ENUM_FIELD_SHORTHAND_C="$BUILD_DIR/stage2_struct_enum_field_shorthand_minimal.c"
STRUCT_ENUM_FIELD_SHORTHAND_O="$BUILD_DIR/stage2_struct_enum_field_shorthand_minimal.o"
ENUM_SHORTHAND_C="$BUILD_DIR/stage2_enum_shorthand_minimal.c"
ENUM_SHORTHAND_O="$BUILD_DIR/stage2_enum_shorthand_minimal.o"
ENUM_SHORTHAND_ARG_C="$BUILD_DIR/stage2_enum_shorthand_arg_minimal.c"
ENUM_SHORTHAND_ARG_O="$BUILD_DIR/stage2_enum_shorthand_arg_minimal.o"
UNION_C="$BUILD_DIR/stage2_union_minimal.c"
UNION_O="$BUILD_DIR/stage2_union_minimal.o"
UNION_SHORTHAND_C="$BUILD_DIR/stage2_union_shorthand_minimal.c"
UNION_SHORTHAND_O="$BUILD_DIR/stage2_union_shorthand_minimal.o"
UNION_BIND_C="$BUILD_DIR/stage2_union_bind_minimal.c"
UNION_BIND_O="$BUILD_DIR/stage2_union_bind_minimal.o"
UNION_TUPLE_BIND_C="$BUILD_DIR/stage2_union_tuple_bind_minimal.c"
UNION_TUPLE_BIND_O="$BUILD_DIR/stage2_union_tuple_bind_minimal.o"
UNION_IF_PATTERN_C="$BUILD_DIR/stage2_union_if_pattern_minimal.c"
UNION_IF_PATTERN_O="$BUILD_DIR/stage2_union_if_pattern_minimal.o"
UNION_IF_MUTABLE_BINDING_C="$BUILD_DIR/stage2_union_if_mutable_binding_minimal.c"
UNION_IF_MUTABLE_BINDING_O="$BUILD_DIR/stage2_union_if_mutable_binding_minimal.o"
UNION_IF_SHORTHAND_PATTERN_C="$BUILD_DIR/stage2_union_if_shorthand_pattern_minimal.c"
UNION_IF_SHORTHAND_PATTERN_O="$BUILD_DIR/stage2_union_if_shorthand_pattern_minimal.o"
UNION_TUPLE_IF_SHORTHAND_PATTERN_C="$BUILD_DIR/stage2_union_tuple_if_shorthand_pattern_minimal.c"
UNION_TUPLE_IF_SHORTHAND_PATTERN_O="$BUILD_DIR/stage2_union_tuple_if_shorthand_pattern_minimal.o"
UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_C="$BUILD_DIR/stage2_union_tuple_if_mutable_shorthand_pattern_minimal.c"
UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_O="$BUILD_DIR/stage2_union_tuple_if_mutable_shorthand_pattern_minimal.o"
UNION_SWITCH_SHORTHAND_PATTERN_C="$BUILD_DIR/stage2_union_switch_shorthand_pattern_minimal.c"
UNION_SWITCH_SHORTHAND_PATTERN_O="$BUILD_DIR/stage2_union_switch_shorthand_pattern_minimal.o"
UNION_SWITCH_MUTABLE_BINDING_C="$BUILD_DIR/stage2_union_switch_mutable_binding_minimal.c"
UNION_SWITCH_MUTABLE_BINDING_O="$BUILD_DIR/stage2_union_switch_mutable_binding_minimal.o"
UNION_TUPLE_SWITCH_MUTABLE_BINDING_C="$BUILD_DIR/stage2_union_tuple_switch_mutable_binding_minimal.c"
UNION_TUPLE_SWITCH_MUTABLE_BINDING_O="$BUILD_DIR/stage2_union_tuple_switch_mutable_binding_minimal.o"
STRUCT_UNION_FIELD_SHORTHAND_C="$BUILD_DIR/stage2_struct_union_field_shorthand_minimal.c"
STRUCT_UNION_FIELD_SHORTHAND_O="$BUILD_DIR/stage2_struct_union_field_shorthand_minimal.o"
BINARY_C="$BUILD_DIR/stage2_binary_ops_minimal.c"
BINARY_O="$BUILD_DIR/stage2_binary_ops_minimal.o"
TERNARY_C="$BUILD_DIR/stage2_ternary_minimal.c"
TERNARY_O="$BUILD_DIR/stage2_ternary_minimal.o"
TERNARY_ENUM_C="$BUILD_DIR/stage2_ternary_enum_minimal.c"
TERNARY_ENUM_O="$BUILD_DIR/stage2_ternary_enum_minimal.o"
LOCALS_C="$BUILD_DIR/stage2_locals_minimal.c"
LOCALS_O="$BUILD_DIR/stage2_locals_minimal.o"
ASSIGN_C="$BUILD_DIR/stage2_assign_minimal.c"
ASSIGN_O="$BUILD_DIR/stage2_assign_minimal.o"
GLOBAL_C="$BUILD_DIR/stage2_global_minimal.c"
GLOBAL_O="$BUILD_DIR/stage2_global_minimal.o"
UNARY_TUPLE_GLOBAL_C="$BUILD_DIR/stage2_unary_tuple_global_decl_minimal.c"
UNARY_TUPLE_GLOBAL_O="$BUILD_DIR/stage2_unary_tuple_global_decl_minimal.o"
INFER_LOCAL_C="$BUILD_DIR/stage2_infer_local_minimal.c"
INFER_LOCAL_O="$BUILD_DIR/stage2_infer_local_minimal.o"
INFER_MUTABLE_LOCAL_C="$BUILD_DIR/stage2_infer_mutable_local_minimal.c"
INFER_MUTABLE_LOCAL_O="$BUILD_DIR/stage2_infer_mutable_local_minimal.o"
UNARY_TUPLE_LOCAL_C="$BUILD_DIR/stage2_unary_tuple_local_decl_minimal.c"
UNARY_TUPLE_LOCAL_O="$BUILD_DIR/stage2_unary_tuple_local_decl_minimal.o"
UNARY_TUPLE_INFER_LOCAL_C="$BUILD_DIR/stage2_unary_tuple_infer_local_decl_minimal.c"
UNARY_TUPLE_INFER_LOCAL_O="$BUILD_DIR/stage2_unary_tuple_infer_local_decl_minimal.o"
TUPLE_DESTRUCTURE_C="$BUILD_DIR/stage2_tuple_destructure_minimal.c"
TUPLE_DESTRUCTURE_O="$BUILD_DIR/stage2_tuple_destructure_minimal.o"
TUPLE_DESTRUCTURE_INFER_C="$BUILD_DIR/stage2_tuple_destructure_infer_minimal.c"
TUPLE_DESTRUCTURE_INFER_O="$BUILD_DIR/stage2_tuple_destructure_infer_minimal.o"
TUPLE_DESTRUCTURE_MUTABLE_INFER_C="$BUILD_DIR/stage2_tuple_destructure_mutable_infer_minimal.c"
TUPLE_DESTRUCTURE_MUTABLE_INFER_O="$BUILD_DIR/stage2_tuple_destructure_mutable_infer_minimal.o"
TUPLE_DESTRUCTURE_GLOBAL_C="$BUILD_DIR/stage2_tuple_destructure_global_minimal.c"
TUPLE_DESTRUCTURE_GLOBAL_O="$BUILD_DIR/stage2_tuple_destructure_global_minimal.o"
TUPLE_DESTRUCTURE_RETURN_C="$BUILD_DIR/stage2_tuple_destructure_return_minimal.c"
TUPLE_DESTRUCTURE_RETURN_O="$BUILD_DIR/stage2_tuple_destructure_return_minimal.o"
TUPLE_VALUE_C="$BUILD_DIR/stage2_tuple_value_minimal.c"
TUPLE_VALUE_O="$BUILD_DIR/stage2_tuple_value_minimal.o"
TUPLE_RETURN_C="$BUILD_DIR/stage2_tuple_return_minimal.c"
TUPLE_RETURN_O="$BUILD_DIR/stage2_tuple_return_minimal.o"
TUPLE_INFER_C="$BUILD_DIR/stage2_tuple_infer_minimal.c"
TUPLE_INFER_O="$BUILD_DIR/stage2_tuple_infer_minimal.o"
INFER_GLOBAL_C="$BUILD_DIR/stage2_infer_global_minimal.c"
INFER_GLOBAL_O="$BUILD_DIR/stage2_infer_global_minimal.o"
OPTIONAL_C="$BUILD_DIR/stage2_optional_minimal.c"
OPTIONAL_O="$BUILD_DIR/stage2_optional_minimal.o"
OPTIONAL_NULL_COMPARE_C="$BUILD_DIR/stage2_optional_null_compare_minimal.c"
OPTIONAL_NULL_COMPARE_O="$BUILD_DIR/stage2_optional_null_compare_minimal.o"
OPTIONAL_IF_NARROW_C="$BUILD_DIR/stage2_optional_if_narrow_minimal.c"
OPTIONAL_IF_NARROW_O="$BUILD_DIR/stage2_optional_if_narrow_minimal.o"
OPTIONAL_ELSE_NARROW_C="$BUILD_DIR/stage2_optional_else_narrow_minimal.c"
OPTIONAL_ELSE_NARROW_O="$BUILD_DIR/stage2_optional_else_narrow_minimal.o"
OPTIONAL_NESTED_ARRAY_C="$BUILD_DIR/stage2_optional_nested_array_minimal.c"
OPTIONAL_NESTED_ARRAY_O="$BUILD_DIR/stage2_optional_nested_array_minimal.o"
OPTIONAL_CHAIN_MEMBER_C="$BUILD_DIR/stage2_optional_chain_member_minimal.c"
OPTIONAL_CHAIN_MEMBER_O="$BUILD_DIR/stage2_optional_chain_member_minimal.o"
OPTIONAL_CHAIN_INDEX_C="$BUILD_DIR/stage2_optional_chain_index_minimal.c"
OPTIONAL_CHAIN_INDEX_O="$BUILD_DIR/stage2_optional_chain_index_minimal.o"
OPTIONAL_CHAIN_NESTED_PURE_BASE_C="$BUILD_DIR/stage2_optional_chain_nested_pure_base_minimal.c"
OPTIONAL_CHAIN_NESTED_PURE_BASE_O="$BUILD_DIR/stage2_optional_chain_nested_pure_base_minimal.o"
MUTABLE_QUALIFIER_C="$BUILD_DIR/stage2_mutable_qualifier_minimal.c"
MUTABLE_QUALIFIER_O="$BUILD_DIR/stage2_mutable_qualifier_minimal.o"
MUTABLE_ARRAY_QUALIFIER_C="$BUILD_DIR/stage2_mutable_array_qualifier_minimal.c"
MUTABLE_ARRAY_QUALIFIER_O="$BUILD_DIR/stage2_mutable_array_qualifier_minimal.o"
STRUCT_OPTIONAL_FIELD_C="$BUILD_DIR/stage2_struct_optional_field_minimal.c"
STRUCT_OPTIONAL_FIELD_O="$BUILD_DIR/stage2_struct_optional_field_minimal.o"
STRUCT_OPTIONAL_FIELD_OMITTED_C="$BUILD_DIR/stage2_struct_optional_field_omitted_minimal.c"
STRUCT_OPTIONAL_FIELD_OMITTED_O="$BUILD_DIR/stage2_struct_optional_field_omitted_minimal.o"
UNARY_TUPLE_RETURN_C="$BUILD_DIR/stage2_unary_tuple_return_minimal.c"
UNARY_TUPLE_RETURN_O="$BUILD_DIR/stage2_unary_tuple_return_minimal.o"
MULTI_C="$BUILD_DIR/stage2_multi_file_minimal.c"
MULTI_O="$BUILD_DIR/stage2_multi_file_minimal.o"
MULTI_ENUM_C="$BUILD_DIR/stage2_multi_file_enum_minimal.c"
MULTI_ENUM_O="$BUILD_DIR/stage2_multi_file_enum_minimal.o"
MULTI_ENUM_SHORTHAND_C="$BUILD_DIR/stage2_multi_file_enum_shorthand_minimal.c"
MULTI_ENUM_SHORTHAND_O="$BUILD_DIR/stage2_multi_file_enum_shorthand_minimal.o"
MULTI_ENUM_SHORTHAND_ARG_C="$BUILD_DIR/stage2_multi_file_enum_shorthand_arg_minimal.c"
MULTI_ENUM_SHORTHAND_ARG_O="$BUILD_DIR/stage2_multi_file_enum_shorthand_arg_minimal.o"
MULTI_ENUM_FIELD_SHORTHAND_C="$BUILD_DIR/stage2_multi_file_enum_field_shorthand_minimal.c"
MULTI_ENUM_FIELD_SHORTHAND_O="$BUILD_DIR/stage2_multi_file_enum_field_shorthand_minimal.o"
MULTI_ENUM_VALUE_C="$BUILD_DIR/stage2_multi_file_enum_value_minimal.c"
MULTI_ENUM_VALUE_O="$BUILD_DIR/stage2_multi_file_enum_value_minimal.o"
MULTI_STRUCT_C="$BUILD_DIR/stage2_multi_file_struct_minimal.c"
MULTI_STRUCT_O="$BUILD_DIR/stage2_multi_file_struct_minimal.o"
MULTI_STRUCT_RETURN_C="$BUILD_DIR/stage2_multi_file_struct_return_minimal.c"
MULTI_STRUCT_RETURN_O="$BUILD_DIR/stage2_multi_file_struct_return_minimal.o"
MULTI_STRUCT_ARRAY_C="$BUILD_DIR/stage2_multi_file_struct_array_minimal.c"
MULTI_STRUCT_ARRAY_O="$BUILD_DIR/stage2_multi_file_struct_array_minimal.o"
STRUCT_C="$BUILD_DIR/stage2_struct_minimal.c"
STRUCT_O="$BUILD_DIR/stage2_struct_minimal.o"
ENUM_C="$BUILD_DIR/stage2_enum_minimal.c"
ENUM_O="$BUILD_DIR/stage2_enum_minimal.o"
ENUM_VALUE_C="$BUILD_DIR/stage2_enum_value_minimal.c"
ENUM_VALUE_O="$BUILD_DIR/stage2_enum_value_minimal.o"
FIELDS_C="$BUILD_DIR/stage2_fields_minimal.c"
FIELDS_O="$BUILD_DIR/stage2_fields_minimal.o"
NESTED_FIELDS_C="$BUILD_DIR/stage2_nested_fields_minimal.c"
NESTED_FIELDS_O="$BUILD_DIR/stage2_nested_fields_minimal.o"
CALL_RESULT_FIELD_C="$BUILD_DIR/stage2_call_result_field_minimal.c"
CALL_RESULT_FIELD_O="$BUILD_DIR/stage2_call_result_field_minimal.o"
PUBLIC_IMPORT_FUNCTION_C="$BUILD_DIR/stage2_public_import_function_minimal.c"
PUBLIC_IMPORT_FUNCTION_O="$BUILD_DIR/stage2_public_import_function_minimal.o"
PUBLIC_IMPORT_TYPE_C="$BUILD_DIR/stage2_public_import_type_minimal.c"
PUBLIC_IMPORT_TYPE_O="$BUILD_DIR/stage2_public_import_type_minimal.o"
ALIAS_IMPORT_FUNCTION_C="$BUILD_DIR/stage2_alias_import_function_minimal.c"
ALIAS_IMPORT_FUNCTION_O="$BUILD_DIR/stage2_alias_import_function_minimal.o"
PUBLIC_ALIAS_FUNCTION_C="$BUILD_DIR/stage2_public_alias_function_minimal.c"
PUBLIC_ALIAS_FUNCTION_O="$BUILD_DIR/stage2_public_alias_function_minimal.o"
ALIAS_IMPORT_TYPE_C="$BUILD_DIR/stage2_alias_import_type_minimal.c"
ALIAS_IMPORT_TYPE_O="$BUILD_DIR/stage2_alias_import_type_minimal.o"
PUBLIC_ALIAS_TYPE_C="$BUILD_DIR/stage2_public_alias_type_minimal.c"
PUBLIC_ALIAS_TYPE_O="$BUILD_DIR/stage2_public_alias_type_minimal.o"
NAMESPACED_IMPORT_C="$BUILD_DIR/stage2_namespaced_import_minimal.c"
NAMESPACED_IMPORT_O="$BUILD_DIR/stage2_namespaced_import_minimal.o"
NAMESPACED_STRUCT_IMPORT_C="$BUILD_DIR/stage2_namespaced_struct_import_minimal.c"
NAMESPACED_STRUCT_IMPORT_O="$BUILD_DIR/stage2_namespaced_struct_import_minimal.o"
NAMESPACED_STRUCT_RETURN_C="$BUILD_DIR/stage2_namespaced_struct_return_minimal.c"
NAMESPACED_STRUCT_RETURN_O="$BUILD_DIR/stage2_namespaced_struct_return_minimal.o"
NAMESPACED_STRUCT_ARRAY_C="$BUILD_DIR/stage2_namespaced_struct_array_minimal.c"
NAMESPACED_STRUCT_ARRAY_O="$BUILD_DIR/stage2_namespaced_struct_array_minimal.o"
NAMESPACED_ENUM_IMPORT_C="$BUILD_DIR/stage2_namespaced_enum_import_minimal.c"
NAMESPACED_ENUM_IMPORT_O="$BUILD_DIR/stage2_namespaced_enum_import_minimal.o"
NAMESPACED_ENUM_SHORTHAND_C="$BUILD_DIR/stage2_namespaced_enum_shorthand_minimal.c"
NAMESPACED_ENUM_SHORTHAND_O="$BUILD_DIR/stage2_namespaced_enum_shorthand_minimal.o"
NAMESPACED_ENUM_FIELD_SHORTHAND_C="$BUILD_DIR/stage2_namespaced_enum_field_shorthand_minimal.c"
NAMESPACED_ENUM_FIELD_SHORTHAND_O="$BUILD_DIR/stage2_namespaced_enum_field_shorthand_minimal.o"
NAMESPACED_ENUM_VALUE_C="$BUILD_DIR/stage2_namespaced_enum_value_minimal.c"
NAMESPACED_ENUM_VALUE_O="$BUILD_DIR/stage2_namespaced_enum_value_minimal.o"
MULTI_SLICE_RETURN_C="$BUILD_DIR/stage2_multi_file_slice_return_minimal.c"
MULTI_SLICE_RETURN_O="$BUILD_DIR/stage2_multi_file_slice_return_minimal.o"
NAMESPACED_SLICE_RETURN_C="$BUILD_DIR/stage2_namespaced_slice_return_minimal.c"
NAMESPACED_SLICE_RETURN_O="$BUILD_DIR/stage2_namespaced_slice_return_minimal.o"
MULTI_SLICE_INDEX_C="$BUILD_DIR/stage2_multi_file_slice_index_minimal.c"
MULTI_SLICE_INDEX_O="$BUILD_DIR/stage2_multi_file_slice_index_minimal.o"
NAMESPACED_SLICE_INDEX_C="$BUILD_DIR/stage2_namespaced_slice_index_minimal.c"
NAMESPACED_SLICE_INDEX_O="$BUILD_DIR/stage2_namespaced_slice_index_minimal.o"
POINTER_C="$BUILD_DIR/stage2_pointer_minimal.c"
POINTER_O="$BUILD_DIR/stage2_pointer_minimal.o"
MULTI_POINTER_C="$BUILD_DIR/stage2_multi_file_pointer_minimal.c"
MULTI_POINTER_O="$BUILD_DIR/stage2_multi_file_pointer_minimal.o"
NAMESPACED_POINTER_C="$BUILD_DIR/stage2_namespaced_pointer_minimal.c"
NAMESPACED_POINTER_O="$BUILD_DIR/stage2_namespaced_pointer_minimal.o"
ARRAY_TO_SLICE_ARG_C="$BUILD_DIR/stage2_array_to_slice_arg_minimal.c"
ARRAY_TO_SLICE_ARG_O="$BUILD_DIR/stage2_array_to_slice_arg_minimal.o"
ARRAY_TO_SLICE_LOCAL_C="$BUILD_DIR/stage2_array_to_slice_local_minimal.c"
ARRAY_TO_SLICE_LOCAL_O="$BUILD_DIR/stage2_array_to_slice_local_minimal.o"
ARRAY_TO_SLICE_ASSIGN_C="$BUILD_DIR/stage2_array_to_slice_assign_minimal.c"
ARRAY_TO_SLICE_ASSIGN_O="$BUILD_DIR/stage2_array_to_slice_assign_minimal.o"
ARRAY_TO_SLICE_RETURN_C="$BUILD_DIR/stage2_array_to_slice_return_minimal.c"
ARRAY_TO_SLICE_RETURN_O="$BUILD_DIR/stage2_array_to_slice_return_minimal.o"

bash "$PROJECT_ROOT/script/build_stage2.sh"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/minimal.jiang" > "$OUT_C"

rg -q '^#include <stdint.h>$' "$OUT_C"
expect_fn_decl 'long long' 'add' 'long long a, long long b' "$OUT_C"
rg -q 'int main\(void\);' "$OUT_C"
rg -q 'return \(a \+ b\);' "$OUT_C"
rg -q 'return .*add\(40, 2\);' "$OUT_C"

cc -x c -std=c99 -Wall -Wextra -Werror -c "$OUT_C" -o "$OUT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/large_minimal.jiang" > "$LARGE_C"
expect_fn_decl 'long long' 'add15' 'long long x' "$LARGE_C"
rg -q 'return .*add15' "$LARGE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$LARGE_C" -o "$LARGE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/bool_minimal.jiang" > "$BOOL_C"
expect_fn_decl 'int' 'flag' 'long long x' "$BOOL_C"
rg -q '^    if \(.*flag\(1\)\) \{$' "$BOOL_C"
rg -q '^    return 1;$' "$BOOL_C"
rg -q '^    return 0;$' "$BOOL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$BOOL_C" -o "$BOOL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/uint8_minimal.jiang" > "$UINT8_C"
expect_fn_decl 'uint8_t' 'id' 'uint8_t value' "$UINT8_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UINT8_C" -o "$UINT8_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/uint8_slice_minimal.jiang" > "$UINT8_SLICE_C"
rg -q '^typedef struct \{$' "$UINT8_SLICE_C"
rg -q '^} Slice_uint8_t;$' "$UINT8_SLICE_C"
expect_fn_decl 'Slice_uint8_t' 'id' 'Slice_uint8_t value' "$UINT8_SLICE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UINT8_SLICE_C" -o "$UINT8_SLICE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/slice_length_minimal.jiang" > "$SLICE_LENGTH_C"
expect_fn_decl 'long long' 'len' 'Slice_uint8_t value' "$SLICE_LENGTH_C"
rg -q 'return value.length;' "$SLICE_LENGTH_C"
rg -q 'return .*len\(\(Slice_uint8_t\)\{ \.ptr = \(uint8_t\*\)"abc", \.length = 3 \}\);' "$SLICE_LENGTH_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$SLICE_LENGTH_C" -o "$SLICE_LENGTH_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/slice_index_minimal.jiang" > "$SLICE_INDEX_C"
expect_fn_decl 'uint8_t' 'pick' 'Slice_uint8_t value' "$SLICE_INDEX_C"
rg -F -q 'return (value.ptr[1]);' "$SLICE_INDEX_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$SLICE_INDEX_C" -o "$SLICE_INDEX_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/slice_assign_minimal.jiang" > "$SLICE_ASSIGN_C"
expect_fn_decl 'void' 'poke' 'Slice_uint8_t value, uint8_t x' "$SLICE_ASSIGN_C"
rg -F -q '((value.ptr[0]) = x);' "$SLICE_ASSIGN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$SLICE_ASSIGN_C" -o "$SLICE_ASSIGN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/slice_return_length_minimal.jiang" > "$SLICE_RETURN_LENGTH_C"
expect_fn_decl 'Slice_uint8_t' 'id' 'Slice_uint8_t value' "$SLICE_RETURN_LENGTH_C"
rg -q 'return .*id\(\(Slice_uint8_t\)\{ \.ptr = \(uint8_t\*\)"abc", \.length = 3 \}\)\.length;' "$SLICE_RETURN_LENGTH_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$SLICE_RETURN_LENGTH_C" -o "$SLICE_RETURN_LENGTH_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/array_minimal.jiang" > "$ARRAY_C"
rg -F -q '    long long arr[5] = { 1, 2, 3, 4, 42 };' "$ARRAY_C"
rg -F -q 'return (arr[4]);' "$ARRAY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ARRAY_C" -o "$ARRAY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/infer_array_length_minimal.jiang" > "$INFER_ARRAY_LENGTH_C"
rg -F -q '    long long values[2] = { 40, 2 };' "$INFER_ARRAY_LENGTH_C"
rg -F -q 'return ((values[0]) + (values[1]));' "$INFER_ARRAY_LENGTH_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$INFER_ARRAY_LENGTH_C" -o "$INFER_ARRAY_LENGTH_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/typed_array_constructor_minimal.jiang" > "$TYPED_ARRAY_CONSTRUCTOR_C"
rg -F -q '    long long pair[2] = { 40, 2 };' "$TYPED_ARRAY_CONSTRUCTOR_C"
rg -F -q 'return ((pair[0]) + (pair[1]));' "$TYPED_ARRAY_CONSTRUCTOR_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TYPED_ARRAY_CONSTRUCTOR_C" -o "$TYPED_ARRAY_CONSTRUCTOR_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/typed_array_constructor_infer_minimal.jiang" > "$TYPED_ARRAY_CONSTRUCTOR_INFER_C"
rg -F -q '    long long pair[2] = { 40, 2 };' "$TYPED_ARRAY_CONSTRUCTOR_INFER_C"
rg -F -q 'return ((pair[0]) + (pair[1]));' "$TYPED_ARRAY_CONSTRUCTOR_INFER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TYPED_ARRAY_CONSTRUCTOR_INFER_C" -o "$TYPED_ARRAY_CONSTRUCTOR_INFER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/array_assign_minimal.jiang" > "$ARRAY_ASSIGN_C"
rg -F -q '    long long arr[3] = { 1, 2, 3 };' "$ARRAY_ASSIGN_C"
rg -F -q '((arr[1]) = 10);' "$ARRAY_ASSIGN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ARRAY_ASSIGN_C" -o "$ARRAY_ASSIGN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/uint8_array_string_minimal.jiang" > "$UINT8_ARRAY_STRING_C"
rg -F -q '    uint8_t text[3] = { 97, 98, 99 };' "$UINT8_ARRAY_STRING_C"
rg -F -q 'return (text[1]);' "$UINT8_ARRAY_STRING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UINT8_ARRAY_STRING_C" -o "$UINT8_ARRAY_STRING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/infer_uint8_array_string_minimal.jiang" > "$INFER_UINT8_ARRAY_STRING_C"
rg -F -q '    uint8_t text[3] = { 97, 98, 99 };' "$INFER_UINT8_ARRAY_STRING_C"
rg -F -q 'return (text[1]);' "$INFER_UINT8_ARRAY_STRING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$INFER_UINT8_ARRAY_STRING_C" -o "$INFER_UINT8_ARRAY_STRING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/nested_array_minimal.jiang" > "$NESTED_ARRAY_C"
rg -F -q '    long long matrix[3][2] = { { 1, 2 }, { 3, 4 }, { 5, 42 } };' "$NESTED_ARRAY_C"
rg -F -q 'return ((matrix[2])[1]);' "$NESTED_ARRAY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NESTED_ARRAY_C" -o "$NESTED_ARRAY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/struct_array_field_minimal.jiang" > "$STRUCT_ARRAY_FIELD_C"
expect_type_start 'struct' 'Buffer' "$STRUCT_ARRAY_FIELD_C"
rg -F -q '    uint8_t text[3];' "$STRUCT_ARRAY_FIELD_C"
rg -q '.*Buffer buf = \(.*Buffer\)\{ \.text = \{ 97, 98, 99 \} \};' "$STRUCT_ARRAY_FIELD_C"
rg -F -q 'return (buf.text[1]);' "$STRUCT_ARRAY_FIELD_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$STRUCT_ARRAY_FIELD_C" -o "$STRUCT_ARRAY_FIELD_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/empty_tuple_return_minimal.jiang" > "$EMPTY_TUPLE_RETURN_C"
expect_fn_decl 'void' 'noop' 'void' "$EMPTY_TUPLE_RETURN_C"
rg -q '^    return;$' "$EMPTY_TUPLE_RETURN_C"
rg -q '^    .*noop\(\);$' "$EMPTY_TUPLE_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$EMPTY_TUPLE_RETURN_C" -o "$EMPTY_TUPLE_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/empty_tuple_bare_return_minimal.jiang" > "$EMPTY_TUPLE_BARE_RETURN_C"
expect_fn_decl 'void' 'noop' 'void' "$EMPTY_TUPLE_BARE_RETURN_C"
rg -q '^    return;$' "$EMPTY_TUPLE_BARE_RETURN_C"
rg -q '^    .*noop\(\);$' "$EMPTY_TUPLE_BARE_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$EMPTY_TUPLE_BARE_RETURN_C" -o "$EMPTY_TUPLE_BARE_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/if_minimal.jiang" > "$IF_C"
expect_fn_decl 'long long' 'choose' 'int flag' "$IF_C"
rg -q '^    if \(flag\) \{$' "$IF_C"
rg -q '^    \} else \{$' "$IF_C"
rg -q '^    return 1;$' "$IF_C"
rg -q '^    return 2;$' "$IF_C"
rg -q 'return .*choose\(0\);' "$IF_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$IF_C" -o "$IF_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/while_minimal.jiang" > "$WHILE_C"
expect_fn_decl 'long long' 'loop_sum' 'long long n' "$WHILE_C"
rg -q '^    while \(i < n\) \{$' "$WHILE_C"
rg -q '\(sum = \(sum \+ i\)\);' "$WHILE_C"
rg -q '\(i = \(i \+ 1\)\);' "$WHILE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$WHILE_C" -o "$WHILE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/break_continue_minimal.jiang" > "$BREAK_CONTINUE_C"
expect_fn_decl 'long long' 'loop_break_continue' 'long long n' "$BREAK_CONTINUE_C"
rg -q '^    continue;$' "$BREAK_CONTINUE_C"
rg -q '^    break;$' "$BREAK_CONTINUE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$BREAK_CONTINUE_C" -o "$BREAK_CONTINUE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_range_minimal.jiang" > "$FOR_RANGE_C"
expect_fn_decl 'long long' 'loop_for' 'long long n' "$FOR_RANGE_C"
rg -q '^    for \(long long i = 0; i < __jiang_for_end_[0-9]+; i = i \+ 1\) \{$' "$FOR_RANGE_C"
rg -q '^    continue;$' "$FOR_RANGE_C"
rg -q '^    break;$' "$FOR_RANGE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_RANGE_C" -o "$FOR_RANGE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_infer_range_minimal.jiang" > "$FOR_INFER_RANGE_C"
expect_fn_decl 'long long' 'loop_for' 'long long n' "$FOR_INFER_RANGE_C"
rg -q '^    for \(long long i = 0; i < __jiang_for_end_[0-9]+; i = i \+ 1\) \{$' "$FOR_INFER_RANGE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_INFER_RANGE_C" -o "$FOR_INFER_RANGE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_item_array_minimal.jiang" > "$FOR_ITEM_ARRAY_C"
expect_fn_decl 'long long' 'sum_items' 'void' "$FOR_ITEM_ARRAY_C"
rg -F -q '    long long values[3] = { 10, 20, 12 };' "$FOR_ITEM_ARRAY_C"
rg -q 'Slice_int64_t __jiang_iter_' "$FOR_ITEM_ARRAY_C"
rg -q 'for \(long long __jiang_index_' "$FOR_ITEM_ARRAY_C"
rg -F -q 'long long item = (__jiang_iter_' "$FOR_ITEM_ARRAY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_ITEM_ARRAY_C" -o "$FOR_ITEM_ARRAY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_indexed_minimal.jiang" > "$FOR_INDEXED_C"
rg -q 'long long i = __jiang_index_' "$FOR_INDEXED_C"
rg -q 'long long item = \(__jiang_iter_.*\.ptr\[__jiang_index_' "$FOR_INDEXED_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_INDEXED_C" -o "$FOR_INDEXED_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_indexed_typed_minimal.jiang" > "$FOR_INDEXED_TYPED_C"
rg -q 'long long i = __jiang_index_' "$FOR_INDEXED_TYPED_C"
rg -q 'long long item = \(__jiang_iter_.*\.ptr\[__jiang_index_' "$FOR_INDEXED_TYPED_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_INDEXED_TYPED_C" -o "$FOR_INDEXED_TYPED_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_indexed_tuple_binding_minimal.jiang" > "$FOR_INDEXED_TUPLE_BINDING_C"
rg -q 'long long i = __jiang_index_' "$FOR_INDEXED_TUPLE_BINDING_C"
rg -q 'Tuple_[0-9][0-9]* __tuple_tmp_' "$FOR_INDEXED_TUPLE_BINDING_C"
rg -q 'long long left = \(__tuple_tmp_[0-9][0-9]*\._0\);' "$FOR_INDEXED_TUPLE_BINDING_C"
rg -q 'long long right = \(__tuple_tmp_[0-9][0-9]*\._1\);' "$FOR_INDEXED_TUPLE_BINDING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_INDEXED_TUPLE_BINDING_C" -o "$FOR_INDEXED_TUPLE_BINDING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_mutable_binding_minimal.jiang" > "$FOR_MUTABLE_BINDING_C"
rg -q 'long long value = \(__jiang_iter_.*\.ptr\[__jiang_index_' "$FOR_MUTABLE_BINDING_C"
rg -q '^    \(value = \(value \+ 1\)\);$' "$FOR_MUTABLE_BINDING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_MUTABLE_BINDING_C" -o "$FOR_MUTABLE_BINDING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_indexed_mutable_tuple_binding_minimal.jiang" > "$FOR_INDEXED_MUTABLE_TUPLE_BINDING_C"
rg -q 'long long i = __jiang_index_' "$FOR_INDEXED_MUTABLE_TUPLE_BINDING_C"
rg -q 'Tuple_[0-9][0-9]* __tuple_tmp_' "$FOR_INDEXED_MUTABLE_TUPLE_BINDING_C"
rg -q 'long long left = \(__tuple_tmp_[0-9][0-9]*\._0\);' "$FOR_INDEXED_MUTABLE_TUPLE_BINDING_C"
rg -q 'long long right = \(__tuple_tmp_[0-9][0-9]*\._1\);' "$FOR_INDEXED_MUTABLE_TUPLE_BINDING_C"
rg -q '^    \(left = \(left \+ i\)\);$' "$FOR_INDEXED_MUTABLE_TUPLE_BINDING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_INDEXED_MUTABLE_TUPLE_BINDING_C" -o "$FOR_INDEXED_MUTABLE_TUPLE_BINDING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_tuple_binding_minimal.jiang" > "$FOR_TUPLE_BINDING_C"
rg -q 'Tuple_[0-9][0-9]* __tuple_tmp_' "$FOR_TUPLE_BINDING_C"
rg -q 'long long left = \(__tuple_tmp_[0-9][0-9]*\._0\);' "$FOR_TUPLE_BINDING_C"
rg -q 'long long right = \(__tuple_tmp_[0-9][0-9]*\._1\);' "$FOR_TUPLE_BINDING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_TUPLE_BINDING_C" -o "$FOR_TUPLE_BINDING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/for_tuple_binding_typed_minimal.jiang" > "$FOR_TUPLE_BINDING_TYPED_C"
rg -q 'Tuple_[0-9][0-9]* __tuple_tmp_' "$FOR_TUPLE_BINDING_TYPED_C"
rg -q 'long long left = \(__tuple_tmp_[0-9][0-9]*\._0\);' "$FOR_TUPLE_BINDING_TYPED_C"
rg -q 'long long right = \(__tuple_tmp_[0-9][0-9]*\._1\);' "$FOR_TUPLE_BINDING_TYPED_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FOR_TUPLE_BINDING_TYPED_C" -o "$FOR_TUPLE_BINDING_TYPED_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/switch_enum_minimal.jiang" > "$SWITCH_ENUM_C"
expect_type_start 'enum' 'Priority' "$SWITCH_ENUM_C"
rg -q 'if \(__jiang_switch_' "$SWITCH_ENUM_C"
rg -q 'Priority_medium' "$SWITCH_ENUM_C"
rg -q '^    return 42;$' "$SWITCH_ENUM_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$SWITCH_ENUM_C" -o "$SWITCH_ENUM_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/enum_shorthand_minimal.jiang" > "$ENUM_SHORTHAND_C"
expect_type_start 'enum' 'HttpStatus' "$ENUM_SHORTHAND_C"
rg -q '^    .*HttpStatus status = .*HttpStatus_ok;$' "$ENUM_SHORTHAND_C"
rg -q '^    return .*HttpStatus_ok;$' "$ENUM_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ENUM_SHORTHAND_C" -o "$ENUM_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/enum_shorthand_arg_minimal.jiang" > "$ENUM_SHORTHAND_ARG_C"
expect_type_start 'enum' 'HttpStatus' "$ENUM_SHORTHAND_ARG_C"
rg -q '^    return .*code\(.*HttpStatus_ok\);$' "$ENUM_SHORTHAND_ARG_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ENUM_SHORTHAND_ARG_C" -o "$ENUM_SHORTHAND_ARG_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/enum_switch_shorthand_minimal.jiang" > "$ENUM_SWITCH_SHORTHAND_C"
expect_type_start 'enum' 'Priority' "$ENUM_SWITCH_SHORTHAND_C"
rg -q 'Priority_medium' "$ENUM_SWITCH_SHORTHAND_C"
rg -q '^    return .*choose\(.*Priority_medium\);$' "$ENUM_SWITCH_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ENUM_SWITCH_SHORTHAND_C" -o "$ENUM_SWITCH_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/struct_enum_field_shorthand_minimal.jiang" > "$STRUCT_ENUM_FIELD_SHORTHAND_C"
expect_type_start 'struct' 'Config' "$STRUCT_ENUM_FIELD_SHORTHAND_C"
rg -q '\.priority = .*Priority_medium' "$STRUCT_ENUM_FIELD_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$STRUCT_ENUM_FIELD_SHORTHAND_C" -o "$STRUCT_ENUM_FIELD_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_minimal.jiang" > "$UNION_C"
expect_type_start 'struct' 'MyUnion' "$UNION_C"
rg -q 'Kind tag;' "$UNION_C"
rg -q 'Kind_b' "$UNION_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_C" -o "$UNION_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_shorthand_minimal.jiang" > "$UNION_SHORTHAND_C"
expect_type_start 'struct' 'MyUnion' "$UNION_SHORTHAND_C"
rg -q '.*MyUnion value = .*Kind_a.*42.*;' "$UNION_SHORTHAND_C"
rg -q '^    return .*Kind_a.*42.*;$' "$UNION_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_SHORTHAND_C" -o "$UNION_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_bind_minimal.jiang" > "$UNION_BIND_C"
expect_type_start 'struct' 'MyUnion' "$UNION_BIND_C"
rg -q 'long long a;' "$UNION_BIND_C"
rg -q 'long long b;' "$UNION_BIND_C"
rg -q 'long long payload = __jiang_switch_' "$UNION_BIND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_BIND_C" -o "$UNION_BIND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_tuple_bind_minimal.jiang" > "$UNION_TUPLE_BIND_C"
expect_type_start 'struct' 'MyUnion' "$UNION_TUPLE_BIND_C"
rg -q '^    long long left = \(__jiang_switch_.*\._0\);$' "$UNION_TUPLE_BIND_C"
rg -q '^    long long right = \(__jiang_switch_.*\._1\);$' "$UNION_TUPLE_BIND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_TUPLE_BIND_C" -o "$UNION_TUPLE_BIND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_if_pattern_minimal.jiang" > "$UNION_IF_PATTERN_C"
expect_type_start 'struct' 'MyUnion' "$UNION_IF_PATTERN_C"
rg -q '__jiang_if_pattern_' "$UNION_IF_PATTERN_C"
rg -q 'long long payload = __jiang_if_pattern_' "$UNION_IF_PATTERN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_IF_PATTERN_C" -o "$UNION_IF_PATTERN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_if_mutable_binding_minimal.jiang" > "$UNION_IF_MUTABLE_BINDING_C"
expect_type_start 'struct' 'MyUnion' "$UNION_IF_MUTABLE_BINDING_C"
rg -q '__jiang_if_pattern_' "$UNION_IF_MUTABLE_BINDING_C"
rg -q '^    long long payload = __jiang_if_pattern_' "$UNION_IF_MUTABLE_BINDING_C"
rg -q '^    \(payload = \(payload \+ 1\)\);$' "$UNION_IF_MUTABLE_BINDING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_IF_MUTABLE_BINDING_C" -o "$UNION_IF_MUTABLE_BINDING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_if_shorthand_pattern_minimal.jiang" > "$UNION_IF_SHORTHAND_PATTERN_C"
expect_type_start 'struct' 'MyUnion' "$UNION_IF_SHORTHAND_PATTERN_C"
rg -q '__jiang_if_pattern_' "$UNION_IF_SHORTHAND_PATTERN_C"
rg -q 'Kind_a' "$UNION_IF_SHORTHAND_PATTERN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_IF_SHORTHAND_PATTERN_C" -o "$UNION_IF_SHORTHAND_PATTERN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_tuple_if_shorthand_pattern_minimal.jiang" > "$UNION_TUPLE_IF_SHORTHAND_PATTERN_C"
expect_type_start 'struct' 'MyUnion' "$UNION_TUPLE_IF_SHORTHAND_PATTERN_C"
rg -q '^    long long left = \(__jiang_if_pattern_.*\._0\);$' "$UNION_TUPLE_IF_SHORTHAND_PATTERN_C"
rg -q '^    long long right = \(__jiang_if_pattern_.*\._1\);$' "$UNION_TUPLE_IF_SHORTHAND_PATTERN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_TUPLE_IF_SHORTHAND_PATTERN_C" -o "$UNION_TUPLE_IF_SHORTHAND_PATTERN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_tuple_if_mutable_shorthand_pattern_minimal.jiang" > "$UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_C"
expect_type_start 'struct' 'MyUnion' "$UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_C"
rg -q '^    long long left = \(__jiang_if_pattern_.*\._0\);$' "$UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_C"
rg -q '^    long long right = \(__jiang_if_pattern_.*\._1\);$' "$UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_C"
rg -q '^    \(left = \(left \+ right\)\);$' "$UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_C" -o "$UNION_TUPLE_IF_MUTABLE_SHORTHAND_PATTERN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_switch_shorthand_pattern_minimal.jiang" > "$UNION_SWITCH_SHORTHAND_PATTERN_C"
expect_type_start 'struct' 'MyUnion' "$UNION_SWITCH_SHORTHAND_PATTERN_C"
rg -q '__jiang_switch_' "$UNION_SWITCH_SHORTHAND_PATTERN_C"
rg -q 'Kind_b' "$UNION_SWITCH_SHORTHAND_PATTERN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_SWITCH_SHORTHAND_PATTERN_C" -o "$UNION_SWITCH_SHORTHAND_PATTERN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_switch_mutable_binding_minimal.jiang" > "$UNION_SWITCH_MUTABLE_BINDING_C"
expect_type_start 'struct' 'MyUnion' "$UNION_SWITCH_MUTABLE_BINDING_C"
rg -q '__jiang_switch_' "$UNION_SWITCH_MUTABLE_BINDING_C"
rg -q '^    long long payload = __jiang_switch_.*\.a;$' "$UNION_SWITCH_MUTABLE_BINDING_C"
rg -q '^    \(payload = \(payload \+ 1\)\);$' "$UNION_SWITCH_MUTABLE_BINDING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_SWITCH_MUTABLE_BINDING_C" -o "$UNION_SWITCH_MUTABLE_BINDING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/union_tuple_switch_mutable_binding_minimal.jiang" > "$UNION_TUPLE_SWITCH_MUTABLE_BINDING_C"
expect_type_start 'struct' 'MyUnion' "$UNION_TUPLE_SWITCH_MUTABLE_BINDING_C"
rg -q '__jiang_switch_' "$UNION_TUPLE_SWITCH_MUTABLE_BINDING_C"
rg -q '^    long long left = \(__jiang_switch_.*\._0\);$' "$UNION_TUPLE_SWITCH_MUTABLE_BINDING_C"
rg -q '^    long long right = \(__jiang_switch_.*\._1\);$' "$UNION_TUPLE_SWITCH_MUTABLE_BINDING_C"
rg -q '^    \(left = \(left \+ right\)\);$' "$UNION_TUPLE_SWITCH_MUTABLE_BINDING_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNION_TUPLE_SWITCH_MUTABLE_BINDING_C" -o "$UNION_TUPLE_SWITCH_MUTABLE_BINDING_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/struct_union_field_shorthand_minimal.jiang" > "$STRUCT_UNION_FIELD_SHORTHAND_C"
expect_type_start 'struct' 'Box' "$STRUCT_UNION_FIELD_SHORTHAND_C"
rg -q '\.value = .*Kind_a.*42' "$STRUCT_UNION_FIELD_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$STRUCT_UNION_FIELD_SHORTHAND_C" -o "$STRUCT_UNION_FIELD_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/binary_ops_minimal.jiang" > "$BINARY_C"
rg -q 'return \(\(a \* b\) - \(a / b\)\);' "$BINARY_C"
rg -q 'if \(a == b\) \{' "$BINARY_C"
rg -q 'if \(a != b\) \{' "$BINARY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$BINARY_C" -o "$BINARY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/ternary_minimal.jiang" > "$TERNARY_C"
rg -q 'return \(\(left > right\) \? \(left \+ 2\) : right\);' "$TERNARY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TERNARY_C" -o "$TERNARY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/ternary_enum_minimal.jiang" > "$TERNARY_ENUM_C"
rg -q '\? .*Priority_high : .*Priority_low' "$TERNARY_ENUM_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TERNARY_ENUM_C" -o "$TERNARY_ENUM_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/locals_minimal.jiang" > "$LOCALS_C"
rg -q '^    long long next = \(value \+ value\);$' "$LOCALS_C"
rg -q '^    long long result = .*twice\(21\);$' "$LOCALS_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$LOCALS_C" -o "$LOCALS_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/assign_minimal.jiang" > "$ASSIGN_C"
rg -q '^    long long value = 1;$' "$ASSIGN_C"
rg -q '^    \(value = \(value \+ x\)\);$' "$ASSIGN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ASSIGN_C" -o "$ASSIGN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/global_minimal.jiang" > "$GLOBAL_C"
rg -q '^long long .*answer = 42;$' "$GLOBAL_C"
rg -q '^int main\(void\);$' "$GLOBAL_C"
rg -q '^    return .*answer;$' "$GLOBAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$GLOBAL_C" -o "$GLOBAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/unary_tuple_global_decl_minimal.jiang" > "$UNARY_TUPLE_GLOBAL_C"
rg -q '^long long .*answer = 42;$' "$UNARY_TUPLE_GLOBAL_C"
rg -q '^    return .*answer;$' "$UNARY_TUPLE_GLOBAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNARY_TUPLE_GLOBAL_C" -o "$UNARY_TUPLE_GLOBAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/infer_local_minimal.jiang" > "$INFER_LOCAL_C"
rg -q '^    long long answer = 42;$' "$INFER_LOCAL_C"
rg -q '^    return answer;$' "$INFER_LOCAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$INFER_LOCAL_C" -o "$INFER_LOCAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/infer_mutable_local_minimal.jiang" > "$INFER_MUTABLE_LOCAL_C"
rg -q '^    long long value = 41;$' "$INFER_MUTABLE_LOCAL_C"
rg -q '^    \(value = \(value \+ 1\)\);$' "$INFER_MUTABLE_LOCAL_C"
rg -q '^    return value;$' "$INFER_MUTABLE_LOCAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$INFER_MUTABLE_LOCAL_C" -o "$INFER_MUTABLE_LOCAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/unary_tuple_local_decl_minimal.jiang" > "$UNARY_TUPLE_LOCAL_C"
expect_fn_decl 'long long' 'forty_two' 'void' "$UNARY_TUPLE_LOCAL_C"
rg -q '^    long long value = .*forty_two\(\);$' "$UNARY_TUPLE_LOCAL_C"
rg -q '^    return value;$' "$UNARY_TUPLE_LOCAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNARY_TUPLE_LOCAL_C" -o "$UNARY_TUPLE_LOCAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/unary_tuple_infer_local_decl_minimal.jiang" > "$UNARY_TUPLE_INFER_LOCAL_C"
rg -q '^    long long value = 42;$' "$UNARY_TUPLE_INFER_LOCAL_C"
rg -q '^    return value;$' "$UNARY_TUPLE_INFER_LOCAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNARY_TUPLE_INFER_LOCAL_C" -o "$UNARY_TUPLE_INFER_LOCAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/tuple_destructure_minimal.jiang" > "$TUPLE_DESTRUCTURE_C"
rg -q '^    long long a = 40;$' "$TUPLE_DESTRUCTURE_C"
rg -q '^    long long b = 2;$' "$TUPLE_DESTRUCTURE_C"
rg -q '^    return \(a \+ b\);$' "$TUPLE_DESTRUCTURE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TUPLE_DESTRUCTURE_C" -o "$TUPLE_DESTRUCTURE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/tuple_destructure_infer_minimal.jiang" > "$TUPLE_DESTRUCTURE_INFER_C"
rg -q '^    long long a = 40;$' "$TUPLE_DESTRUCTURE_INFER_C"
rg -q '^    long long b = 2;$' "$TUPLE_DESTRUCTURE_INFER_C"
rg -q '^    return \(a \+ b\);$' "$TUPLE_DESTRUCTURE_INFER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TUPLE_DESTRUCTURE_INFER_C" -o "$TUPLE_DESTRUCTURE_INFER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/tuple_destructure_mutable_infer_minimal.jiang" > "$TUPLE_DESTRUCTURE_MUTABLE_INFER_C"
rg -q '^    long long left = 1;$' "$TUPLE_DESTRUCTURE_MUTABLE_INFER_C"
rg -q '^    long long right = 41;$' "$TUPLE_DESTRUCTURE_MUTABLE_INFER_C"
rg -q '^    \(right = \(right \+ left\)\);$' "$TUPLE_DESTRUCTURE_MUTABLE_INFER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TUPLE_DESTRUCTURE_MUTABLE_INFER_C" -o "$TUPLE_DESTRUCTURE_MUTABLE_INFER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/tuple_destructure_global_minimal.jiang" > "$TUPLE_DESTRUCTURE_GLOBAL_C"
rg -q '^long long .*left = 40;$' "$TUPLE_DESTRUCTURE_GLOBAL_C"
rg -q '^long long .*right = 2;$' "$TUPLE_DESTRUCTURE_GLOBAL_C"
rg -q '^    return \(.*left \+ .*right\);$' "$TUPLE_DESTRUCTURE_GLOBAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TUPLE_DESTRUCTURE_GLOBAL_C" -o "$TUPLE_DESTRUCTURE_GLOBAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/tuple_destructure_return_minimal.jiang" > "$TUPLE_DESTRUCTURE_RETURN_C"
rg -q '^typedef struct \{$' "$TUPLE_DESTRUCTURE_RETURN_C"
rg -q '^    Tuple_[0-9][0-9]* __tuple_tmp_[0-9][0-9]* = .*pair\(\);$' "$TUPLE_DESTRUCTURE_RETURN_C"
rg -q '^    long long a = \(__tuple_tmp_[0-9][0-9]*\._0\);$' "$TUPLE_DESTRUCTURE_RETURN_C"
rg -q '^    long long b = \(__tuple_tmp_[0-9][0-9]*\._1\);$' "$TUPLE_DESTRUCTURE_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TUPLE_DESTRUCTURE_RETURN_C" -o "$TUPLE_DESTRUCTURE_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/tuple_value_minimal.jiang" > "$TUPLE_VALUE_C"
rg -q '^typedef struct \{$' "$TUPLE_VALUE_C"
rg -q '^Tuple_[0-9][0-9]* .*pair = \(Tuple_[0-9][0-9]*\)\{ \._0 = 40, \._1 = 2 \};$' "$TUPLE_VALUE_C"
rg -q '^    return \(\(.*pair\._0\) \+ \(.*pair\._1\)\);$' "$TUPLE_VALUE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TUPLE_VALUE_C" -o "$TUPLE_VALUE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/tuple_return_minimal.jiang" > "$TUPLE_RETURN_C"
rg -q '^typedef struct \{$' "$TUPLE_RETURN_C"
expect_fn_decl 'Tuple_[0-9][0-9]*' 'pair' 'void' "$TUPLE_RETURN_C"
rg -q '^    Tuple_[0-9][0-9]* value = .*pair\(\);$' "$TUPLE_RETURN_C"
rg -q '^    return \(\(value\._0\) \+ \(value\._1\)\);$' "$TUPLE_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TUPLE_RETURN_C" -o "$TUPLE_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/tuple_infer_minimal.jiang" > "$TUPLE_INFER_C"
rg -q '^typedef struct \{$' "$TUPLE_INFER_C"
rg -q '^    Tuple_[0-9][0-9]* pair = \(Tuple_[0-9][0-9]*\)\{ \._0 = 40, \._1 = 2 \};$' "$TUPLE_INFER_C"
rg -q '^    return \(\(pair\._0\) \+ \(pair\._1\)\);$' "$TUPLE_INFER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$TUPLE_INFER_C" -o "$TUPLE_INFER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/infer_global_minimal.jiang" > "$INFER_GLOBAL_C"
rg -q '^long long .*answer = 42;$' "$INFER_GLOBAL_C"
rg -q '^    return .*answer;$' "$INFER_GLOBAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$INFER_GLOBAL_C" -o "$INFER_GLOBAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/optional_minimal.jiang" > "$OPTIONAL_C"
rg -q '^typedef struct \{$' "$OPTIONAL_C"
rg -q '^    int is_some;$' "$OPTIONAL_C"
rg -q '^    Optional_[0-9][0-9]*_t none = \(Optional_[0-9][0-9]*_t\)\{ \.is_some = 0 \};$' "$OPTIONAL_C"
rg -q '^    Optional_[0-9][0-9]*_t some = \(Optional_[0-9][0-9]*_t\)\{ \.is_some = 1, \.value = 42 \};$' "$OPTIONAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$OPTIONAL_C" -o "$OPTIONAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/optional_null_compare_minimal.jiang" > "$OPTIONAL_NULL_COMPARE_C"
rg -q '\.is_some == 0' "$OPTIONAL_NULL_COMPARE_C"
rg -q '\.is_some != 0' "$OPTIONAL_NULL_COMPARE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$OPTIONAL_NULL_COMPARE_C" -o "$OPTIONAL_NULL_COMPARE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/optional_if_narrow_minimal.jiang" > "$OPTIONAL_IF_NARROW_C"
rg -q '\.is_some != 0' "$OPTIONAL_IF_NARROW_C"
rg -q '\.value' "$OPTIONAL_IF_NARROW_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$OPTIONAL_IF_NARROW_C" -o "$OPTIONAL_IF_NARROW_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/optional_else_narrow_minimal.jiang" > "$OPTIONAL_ELSE_NARROW_C"
rg -q '\.is_some == 0' "$OPTIONAL_ELSE_NARROW_C"
rg -q '\.value' "$OPTIONAL_ELSE_NARROW_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$OPTIONAL_ELSE_NARROW_C" -o "$OPTIONAL_ELSE_NARROW_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/optional_nested_array_minimal.jiang" > "$OPTIONAL_NESTED_ARRAY_C"
rg -q '^    Optional_[0-9][0-9]*_t rows\[3\]\[2\] = ' "$OPTIONAL_NESTED_ARRAY_C"
rg -q '^    Optional_[0-9][0-9]*_t value = \(\(rows\[0\]\)\[1\]\);$' "$OPTIONAL_NESTED_ARRAY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$OPTIONAL_NESTED_ARRAY_C" -o "$OPTIONAL_NESTED_ARRAY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/optional_chain_member_minimal.jiang" > "$OPTIONAL_CHAIN_MEMBER_C"
rg -q '\.profile' "$OPTIONAL_CHAIN_MEMBER_C"
rg -q '\.age' "$OPTIONAL_CHAIN_MEMBER_C"
rg -q '\.is_some != 0' "$OPTIONAL_CHAIN_MEMBER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$OPTIONAL_CHAIN_MEMBER_C" -o "$OPTIONAL_CHAIN_MEMBER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/optional_chain_index_minimal.jiang" > "$OPTIONAL_CHAIN_INDEX_C"
rg -q '\.is_some != 0' "$OPTIONAL_CHAIN_INDEX_C"
rg -q '\[0\]' "$OPTIONAL_CHAIN_INDEX_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$OPTIONAL_CHAIN_INDEX_C" -o "$OPTIONAL_CHAIN_INDEX_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/optional_chain_nested_pure_base_minimal.jiang" > "$OPTIONAL_CHAIN_NESTED_PURE_BASE_C"
rg -q 'users\[0\]' "$OPTIONAL_CHAIN_NESTED_PURE_BASE_C"
rg -q '\.profile' "$OPTIONAL_CHAIN_NESTED_PURE_BASE_C"
rg -q '\.is_some != 0' "$OPTIONAL_CHAIN_NESTED_PURE_BASE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$OPTIONAL_CHAIN_NESTED_PURE_BASE_C" -o "$OPTIONAL_CHAIN_NESTED_PURE_BASE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/mutable_qualifier_minimal.jiang" > "$MUTABLE_QUALIFIER_C"
expect_fn_decl 'long long' 'bump' 'long long value' "$MUTABLE_QUALIFIER_C"
rg -q '^    \(value = \(value \+ 1\)\);$' "$MUTABLE_QUALIFIER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MUTABLE_QUALIFIER_C" -o "$MUTABLE_QUALIFIER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/mutable_array_qualifier_minimal.jiang" > "$MUTABLE_ARRAY_QUALIFIER_C"
rg -F -q '    long long inner[2] = { 20, 22 };' "$MUTABLE_ARRAY_QUALIFIER_C"
rg -F -q '    long long outer[2] = { 20, 22 };' "$MUTABLE_ARRAY_QUALIFIER_C"
rg -F -q 'return ((inner[0]) + (outer[1]));' "$MUTABLE_ARRAY_QUALIFIER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MUTABLE_ARRAY_QUALIFIER_C" -o "$MUTABLE_ARRAY_QUALIFIER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/struct_optional_field_minimal.jiang" > "$STRUCT_OPTIONAL_FIELD_C"
expect_type_start 'struct' 'User' "$STRUCT_OPTIONAL_FIELD_C"
rg -q 'Optional_[0-9][0-9]*_t nick_name;' "$STRUCT_OPTIONAL_FIELD_C"
rg -q '\.nick_name = \(Optional_[0-9][0-9]*_t\)\{ \.is_some = 0 \}' "$STRUCT_OPTIONAL_FIELD_C"
rg -q '\.nick_name = \(Optional_[0-9][0-9]*_t\)\{ \.is_some = 1, \.value = 42 \}' "$STRUCT_OPTIONAL_FIELD_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$STRUCT_OPTIONAL_FIELD_C" -o "$STRUCT_OPTIONAL_FIELD_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/struct_optional_field_omitted_minimal.jiang" > "$STRUCT_OPTIONAL_FIELD_OMITTED_C"
expect_type_start 'struct' 'User' "$STRUCT_OPTIONAL_FIELD_OMITTED_C"
rg -q 'Optional_[0-9][0-9]*_t nick_name;' "$STRUCT_OPTIONAL_FIELD_OMITTED_C"
rg -q '\.age = 18' "$STRUCT_OPTIONAL_FIELD_OMITTED_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$STRUCT_OPTIONAL_FIELD_OMITTED_C" -o "$STRUCT_OPTIONAL_FIELD_OMITTED_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/unary_tuple_return_minimal.jiang" > "$UNARY_TUPLE_RETURN_C"
expect_fn_decl 'long long' 'forty_two' 'void' "$UNARY_TUPLE_RETURN_C"
rg -q '^    return .*forty_two\(\);$' "$UNARY_TUPLE_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$UNARY_TUPLE_RETURN_C" -o "$UNARY_TUPLE_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_minimal.jiang" > "$MULTI_C"
expect_fn_decl 'long long' 'helper_add' 'long long a, long long b' "$MULTI_C"
rg -q 'return .*helper_add\(20, 22\);' "$MULTI_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_C" -o "$MULTI_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_enum_minimal.jiang" > "$MULTI_ENUM_C"
expect_type_start 'enum' 'Mode' "$MULTI_ENUM_C"
rg -q '^    .*Mode_read = 0,$' "$MULTI_ENUM_C"
rg -q '^    .*Mode_write = 1$' "$MULTI_ENUM_C"
rg -q '^    .*Mode mode = .*Mode_read;$' "$MULTI_ENUM_C"
rg -q '^    if \(mode == .*Mode_read\) \{$' "$MULTI_ENUM_C"
rg -q '^    return 1;$' "$MULTI_ENUM_C"
rg -q '^    return 0;$' "$MULTI_ENUM_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_ENUM_C" -o "$MULTI_ENUM_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_enum_shorthand_minimal.jiang" > "$MULTI_ENUM_SHORTHAND_C"
expect_type_start 'enum' 'Mode' "$MULTI_ENUM_SHORTHAND_C"
rg -q '^    .*Mode mode = .*Mode_read;$' "$MULTI_ENUM_SHORTHAND_C"
rg -q '^    if \(mode == .*Mode_read\) \{$' "$MULTI_ENUM_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_ENUM_SHORTHAND_C" -o "$MULTI_ENUM_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_enum_shorthand_arg_minimal.jiang" > "$MULTI_ENUM_SHORTHAND_ARG_C"
expect_type_start 'enum' 'Mode' "$MULTI_ENUM_SHORTHAND_ARG_C"
rg -q '^    return .*code\(.*Mode_read\);$' "$MULTI_ENUM_SHORTHAND_ARG_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_ENUM_SHORTHAND_ARG_C" -o "$MULTI_ENUM_SHORTHAND_ARG_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_enum_field_shorthand_minimal.jiang" > "$MULTI_ENUM_FIELD_SHORTHAND_C"
expect_type_start 'struct' 'Config' "$MULTI_ENUM_FIELD_SHORTHAND_C"
rg -q '\.mode = .*Mode_read' "$MULTI_ENUM_FIELD_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_ENUM_FIELD_SHORTHAND_C" -o "$MULTI_ENUM_FIELD_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_enum_value_minimal.jiang" > "$MULTI_ENUM_VALUE_C"
expect_type_start 'enum' 'Mode' "$MULTI_ENUM_VALUE_C"
rg -q '^    .*Mode_read = 3,' "$MULTI_ENUM_VALUE_C"
rg -q '^    .*Mode_write = 7$' "$MULTI_ENUM_VALUE_C"
rg -q '^    return mode;$' "$MULTI_ENUM_VALUE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_ENUM_VALUE_C" -o "$MULTI_ENUM_VALUE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_struct_minimal.jiang" > "$MULTI_STRUCT_C"
expect_type_start 'struct' 'Pair' "$MULTI_STRUCT_C"
expect_type_end 'Pair' "$MULTI_STRUCT_C"
rg -q '.*Pair pair = \(.*Pair\)\{ \.left = 20, \.right = 22 \};' "$MULTI_STRUCT_C"
rg -q 'return \(pair.left \+ pair.right\);' "$MULTI_STRUCT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_STRUCT_C" -o "$MULTI_STRUCT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_struct_return_minimal.jiang" > "$MULTI_STRUCT_RETURN_C"
expect_fn_decl '.*Pair' 'make_pair' 'void' "$MULTI_STRUCT_RETURN_C"
rg -q 'return \(.*make_pair\(\)\.left \+ .*make_pair\(\)\.right\);' "$MULTI_STRUCT_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_STRUCT_RETURN_C" -o "$MULTI_STRUCT_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_struct_array_minimal.jiang" > "$MULTI_STRUCT_ARRAY_C"
expect_type_start 'struct' 'Buffer' "$MULTI_STRUCT_ARRAY_C"
rg -F -q '    uint8_t text[3];' "$MULTI_STRUCT_ARRAY_C"
expect_fn_decl 'uint8_t' 'middle' '.*Buffer buf' "$MULTI_STRUCT_ARRAY_C"
rg -q '.*Buffer buf = \(.*Buffer\)\{ \.text = \{ 97, 98, 99 \} \};' "$MULTI_STRUCT_ARRAY_C"
rg -q 'return .*middle\(buf\);' "$MULTI_STRUCT_ARRAY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_STRUCT_ARRAY_C" -o "$MULTI_STRUCT_ARRAY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/struct_minimal.jiang" > "$STRUCT_C"
expect_type_start 'struct' 'Pair' "$STRUCT_C"
expect_type_end 'Pair' "$STRUCT_C"
expect_fn_decl 'long long' 'sum_pair' '.*Pair pair' "$STRUCT_C"
rg -q 'return \(pair.left \+ pair.right\);' "$STRUCT_C"
rg -q '.*Pair pair = \(.*Pair\)\{ \.left = 20, \.right = 22 \};' "$STRUCT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$STRUCT_C" -o "$STRUCT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/enum_minimal.jiang" > "$ENUM_C"
expect_type_start 'enum' 'Mode' "$ENUM_C"
rg -q '^    .*Mode_read = 0,$' "$ENUM_C"
rg -q '^    .*Mode_write = 1$' "$ENUM_C"
expect_type_end 'Mode' "$ENUM_C"
rg -q 'if \(mode == .*Mode_read\) \{' "$ENUM_C"
rg -q 'return .*code\(.*Mode_write\);' "$ENUM_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ENUM_C" -o "$ENUM_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/enum_value_minimal.jiang" > "$ENUM_VALUE_C"
expect_type_start 'enum' 'Status' "$ENUM_VALUE_C"
rg -q '^    .*Status_pending = 1,' "$ENUM_VALUE_C"
rg -q '^    .*Status_done = 42$' "$ENUM_VALUE_C"
expect_type_end 'Status' "$ENUM_VALUE_C"
rg -q '^    return .*Status_done;$' "$ENUM_VALUE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ENUM_VALUE_C" -o "$ENUM_VALUE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/fields_minimal.jiang" > "$FIELDS_C"
rg -q '.*Pair pair = \(.*Pair\)\{ \.left = 1, \.right = 2 \};' "$FIELDS_C"
rg -q '\(pair.left = \(pair.left \+ pair.right\)\);' "$FIELDS_C"
rg -q '^    return pair.left;$' "$FIELDS_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$FIELDS_C" -o "$FIELDS_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/nested_fields_minimal.jiang" > "$NESTED_FIELDS_C"
expect_type_start 'struct' 'Point' "$NESTED_FIELDS_C"
expect_type_start 'struct' 'Box' "$NESTED_FIELDS_C"
rg -q 'return box.point.x;' "$NESTED_FIELDS_C"
rg -q '.*Box box = \(.*Box\)\{ \.point = \(.*Point\)\{ \.x = 42 \} \};' "$NESTED_FIELDS_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NESTED_FIELDS_C" -o "$NESTED_FIELDS_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/call_result_field_minimal.jiang" > "$CALL_RESULT_FIELD_C"
expect_fn_decl '.*Box' 'make_box' 'void' "$CALL_RESULT_FIELD_C"
rg -q 'return .*make_box\(\)\.point\.x;' "$CALL_RESULT_FIELD_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$CALL_RESULT_FIELD_C" -o "$CALL_RESULT_FIELD_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/public_import_function_minimal.jiang" > "$PUBLIC_IMPORT_FUNCTION_C"
expect_fn_decl 'long long' 'public_add' 'long long a, long long b' "$PUBLIC_IMPORT_FUNCTION_C"
rg -q 'return .*public_add\(20, 22\);' "$PUBLIC_IMPORT_FUNCTION_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$PUBLIC_IMPORT_FUNCTION_C" -o "$PUBLIC_IMPORT_FUNCTION_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/public_import_type_minimal.jiang" > "$PUBLIC_IMPORT_TYPE_C"
expect_type_start 'struct' 'PublicPair' "$PUBLIC_IMPORT_TYPE_C"
rg -q '.*PublicPair pair = \(.*PublicPair\)\{ \.left = 20, \.right = 22 \};' "$PUBLIC_IMPORT_TYPE_C"
rg -q 'return \(pair.left \+ pair.right\);' "$PUBLIC_IMPORT_TYPE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$PUBLIC_IMPORT_TYPE_C" -o "$PUBLIC_IMPORT_TYPE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/alias_import_function_minimal.jiang" > "$ALIAS_IMPORT_FUNCTION_C"
expect_fn_decl 'long long' 'public_add' 'long long a, long long b' "$ALIAS_IMPORT_FUNCTION_C"
rg -q 'return .*public_add\(20, 22\);' "$ALIAS_IMPORT_FUNCTION_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ALIAS_IMPORT_FUNCTION_C" -o "$ALIAS_IMPORT_FUNCTION_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/public_alias_function_minimal.jiang" > "$PUBLIC_ALIAS_FUNCTION_C"
expect_fn_decl 'long long' 'public_add' 'long long a, long long b' "$PUBLIC_ALIAS_FUNCTION_C"
rg -q 'return .*public_add\(20, 22\);' "$PUBLIC_ALIAS_FUNCTION_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$PUBLIC_ALIAS_FUNCTION_C" -o "$PUBLIC_ALIAS_FUNCTION_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/alias_import_type_minimal.jiang" > "$ALIAS_IMPORT_TYPE_C"
expect_type_start 'struct' 'PublicPair' "$ALIAS_IMPORT_TYPE_C"
rg -q '.*PublicPair pair = \(.*PublicPair\)\{ \.left = 20, \.right = 22 \};' "$ALIAS_IMPORT_TYPE_C"
rg -q 'return \(pair.left \+ pair.right\);' "$ALIAS_IMPORT_TYPE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ALIAS_IMPORT_TYPE_C" -o "$ALIAS_IMPORT_TYPE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/public_alias_type_minimal.jiang" > "$PUBLIC_ALIAS_TYPE_C"
expect_type_start 'struct' 'PublicPair' "$PUBLIC_ALIAS_TYPE_C"
rg -q '.*PublicPair pair = \(.*PublicPair\)\{ \.left = 20, \.right = 22 \};' "$PUBLIC_ALIAS_TYPE_C"
rg -q 'return \(pair.left \+ pair.right\);' "$PUBLIC_ALIAS_TYPE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$PUBLIC_ALIAS_TYPE_C" -o "$PUBLIC_ALIAS_TYPE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_import_minimal.jiang" > "$NAMESPACED_IMPORT_C"
expect_fn_decl 'long long' 'helper_add' 'long long a, long long b' "$NAMESPACED_IMPORT_C"
rg -q 'return .*helper_add\(20, 22\);' "$NAMESPACED_IMPORT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_IMPORT_C" -o "$NAMESPACED_IMPORT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_struct_import_minimal.jiang" > "$NAMESPACED_STRUCT_IMPORT_C"
expect_type_start 'struct' 'Pair' "$NAMESPACED_STRUCT_IMPORT_C"
rg -q '.*Pair pair = \(.*Pair\)\{ \.left = 20, \.right = 22 \};' "$NAMESPACED_STRUCT_IMPORT_C"
rg -q 'return \(pair.left \+ pair.right\);' "$NAMESPACED_STRUCT_IMPORT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_STRUCT_IMPORT_C" -o "$NAMESPACED_STRUCT_IMPORT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_struct_return_minimal.jiang" > "$NAMESPACED_STRUCT_RETURN_C"
expect_fn_decl '.*Pair' 'make_pair' 'void' "$NAMESPACED_STRUCT_RETURN_C"
rg -q 'return \(.*make_pair\(\)\.left \+ .*make_pair\(\)\.right\);' "$NAMESPACED_STRUCT_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_STRUCT_RETURN_C" -o "$NAMESPACED_STRUCT_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_struct_array_minimal.jiang" > "$NAMESPACED_STRUCT_ARRAY_C"
expect_type_start 'struct' 'Buffer' "$NAMESPACED_STRUCT_ARRAY_C"
expect_fn_decl 'uint8_t' 'middle' '.*Buffer buf' "$NAMESPACED_STRUCT_ARRAY_C"
rg -q '.*Buffer buf = \(.*Buffer\)\{ \.text = \{ 97, 98, 99 \} \};' "$NAMESPACED_STRUCT_ARRAY_C"
rg -q 'return .*middle\(buf\);' "$NAMESPACED_STRUCT_ARRAY_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_STRUCT_ARRAY_C" -o "$NAMESPACED_STRUCT_ARRAY_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_enum_import_minimal.jiang" > "$NAMESPACED_ENUM_IMPORT_C"
expect_type_start 'enum' 'Mode' "$NAMESPACED_ENUM_IMPORT_C"
rg -q '^    .*Mode mode = .*Mode_read;$' "$NAMESPACED_ENUM_IMPORT_C"
rg -q '^    if \(mode == .*Mode_read\) \{$' "$NAMESPACED_ENUM_IMPORT_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_ENUM_IMPORT_C" -o "$NAMESPACED_ENUM_IMPORT_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_enum_shorthand_minimal.jiang" > "$NAMESPACED_ENUM_SHORTHAND_C"
expect_type_start 'enum' 'Mode' "$NAMESPACED_ENUM_SHORTHAND_C"
rg -q '^    .*Mode mode = .*Mode_read;$' "$NAMESPACED_ENUM_SHORTHAND_C"
rg -q '^    if \(mode == .*Mode_read\) \{$' "$NAMESPACED_ENUM_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_ENUM_SHORTHAND_C" -o "$NAMESPACED_ENUM_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_enum_field_shorthand_minimal.jiang" > "$NAMESPACED_ENUM_FIELD_SHORTHAND_C"
expect_type_start 'struct' 'Config' "$NAMESPACED_ENUM_FIELD_SHORTHAND_C"
rg -q '\.mode = .*Mode_read' "$NAMESPACED_ENUM_FIELD_SHORTHAND_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_ENUM_FIELD_SHORTHAND_C" -o "$NAMESPACED_ENUM_FIELD_SHORTHAND_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_enum_value_minimal.jiang" > "$NAMESPACED_ENUM_VALUE_C"
expect_type_start 'enum' 'Mode' "$NAMESPACED_ENUM_VALUE_C"
rg -q '^    .*Mode_read = 3,' "$NAMESPACED_ENUM_VALUE_C"
rg -q '^    .*Mode_write = 7$' "$NAMESPACED_ENUM_VALUE_C"
rg -q '^    return .*Mode_read;$' "$NAMESPACED_ENUM_VALUE_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_ENUM_VALUE_C" -o "$NAMESPACED_ENUM_VALUE_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_slice_return_minimal.jiang" > "$MULTI_SLICE_RETURN_C"
expect_fn_decl 'Slice_uint8_t' 'expose' 'void' "$MULTI_SLICE_RETURN_C"
rg -q 'return .*expose\(\)\.length;' "$MULTI_SLICE_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_SLICE_RETURN_C" -o "$MULTI_SLICE_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_slice_return_minimal.jiang" > "$NAMESPACED_SLICE_RETURN_C"
expect_fn_decl 'Slice_uint8_t' 'expose' 'void' "$NAMESPACED_SLICE_RETURN_C"
rg -q 'return .*expose\(\)\.length;' "$NAMESPACED_SLICE_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_SLICE_RETURN_C" -o "$NAMESPACED_SLICE_RETURN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_slice_index_minimal.jiang" > "$MULTI_SLICE_INDEX_C"
rg -q 'if \(\(.*expose\(\)\.ptr\[1\]\) == \(.*expose\(\)\.ptr\[1\]\)\) \{' "$MULTI_SLICE_INDEX_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_SLICE_INDEX_C" -o "$MULTI_SLICE_INDEX_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_slice_index_minimal.jiang" > "$NAMESPACED_SLICE_INDEX_C"
rg -q 'if \(\(.*expose\(\)\.ptr\[1\]\) == \(.*expose\(\)\.ptr\[1\]\)\) \{' "$NAMESPACED_SLICE_INDEX_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_SLICE_INDEX_C" -o "$NAMESPACED_SLICE_INDEX_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/pointer_minimal.jiang" > "$POINTER_C"
expect_fn_decl 'long long' 'read' 'long long\* p' "$POINTER_C"
rg -q '^    long long\* p = \(&value\);$' "$POINTER_C"
rg -q '^\s*\(\(\*p\) = \(\(\*p\) \+ 1\)\);$' "$POINTER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$POINTER_C" -o "$POINTER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/multi_file_pointer_minimal.jiang" > "$MULTI_POINTER_C"
expect_fn_decl 'long long' 'read' 'long long\* p' "$MULTI_POINTER_C"
expect_fn_decl 'void' 'bump' 'long long\* p' "$MULTI_POINTER_C"
rg -q '^\s*.*bump\(\(&value\)\);$' "$MULTI_POINTER_C"
rg -q '^\s*return .*read\(\(&value\)\);$' "$MULTI_POINTER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$MULTI_POINTER_C" -o "$MULTI_POINTER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/namespaced_pointer_minimal.jiang" > "$NAMESPACED_POINTER_C"
expect_fn_decl 'long long' 'read' 'long long\* p' "$NAMESPACED_POINTER_C"
expect_fn_decl 'void' 'bump' 'long long\* p' "$NAMESPACED_POINTER_C"
rg -q '^\s*.*bump\(\(&value\)\);$' "$NAMESPACED_POINTER_C"
rg -q '^\s*return .*read\(\(&value\)\);$' "$NAMESPACED_POINTER_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$NAMESPACED_POINTER_C" -o "$NAMESPACED_POINTER_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/array_to_slice_arg_minimal.jiang" > "$ARRAY_TO_SLICE_ARG_C"
expect_fn_decl 'int' 'is_b' 'Slice_uint8_t value' "$ARRAY_TO_SLICE_ARG_C"
rg -q '^    uint8_t probe = \(value.ptr\[1\]\);$' "$ARRAY_TO_SLICE_ARG_C"
rg -q 'if \(.*is_b\(\(Slice_uint8_t\)\{ \.ptr = \(uint8_t\*\)text, \.length = 3 \}\)\) \{' "$ARRAY_TO_SLICE_ARG_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ARRAY_TO_SLICE_ARG_C" -o "$ARRAY_TO_SLICE_ARG_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/array_to_slice_local_minimal.jiang" > "$ARRAY_TO_SLICE_LOCAL_C"
rg -F -q 'Slice_uint8_t view = (Slice_uint8_t){ .ptr = (uint8_t*)text, .length = 3 };' "$ARRAY_TO_SLICE_LOCAL_C"
rg -F -q 'uint8_t probe = (view.ptr[2]);' "$ARRAY_TO_SLICE_LOCAL_C"
rg -F -q 'if ((view.ptr[2]) == probe) {' "$ARRAY_TO_SLICE_LOCAL_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ARRAY_TO_SLICE_LOCAL_C" -o "$ARRAY_TO_SLICE_LOCAL_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/array_to_slice_assign_minimal.jiang" > "$ARRAY_TO_SLICE_ASSIGN_C"
rg -F -q '(view = (Slice_uint8_t){ .ptr = (uint8_t*)text, .length = 3 });' "$ARRAY_TO_SLICE_ASSIGN_C"
rg -F -q 'uint8_t probe = (view.ptr[0]);' "$ARRAY_TO_SLICE_ASSIGN_C"
rg -F -q 'if ((view.ptr[0]) == probe) {' "$ARRAY_TO_SLICE_ASSIGN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ARRAY_TO_SLICE_ASSIGN_C" -o "$ARRAY_TO_SLICE_ASSIGN_O"

"$BUILD_DIR/stage2c" "$PROJECT_ROOT/compiler/tests/samples/array_to_slice_return_minimal.jiang" > "$ARRAY_TO_SLICE_RETURN_C"
expect_fn_decl 'Slice_uint8_t' 'expose' 'void' "$ARRAY_TO_SLICE_RETURN_C"
rg -F -q 'return (Slice_uint8_t){ .ptr = (uint8_t*)text, .length = 3 };' "$ARRAY_TO_SLICE_RETURN_C"
cc -x c -std=c99 -Wall -Wextra -Werror -c "$ARRAY_TO_SLICE_RETURN_C" -o "$ARRAY_TO_SLICE_RETURN_O"

echo "stage2 emit-c smoke passed"
